// Generato automaticamente il 2026-08-02 12:14 UTC da scripts/fetch_news.py
// NON modificare manualmente: viene sovrascritto ogni ora dalla GitHub Action.
var NEWS_TIMESTAMP = 1785672846;
const FEED_META = {"successful_sources": 19, "failed_sources": [], "total_sources": 19, "total_articles": 34};

const RSS_SOURCES = [
  {
    "name": "ANSA",
    "url": "https://www.ansa.it/sito/ansait_rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "AGI",
    "url": "https://www.agi.it/politica/rss",
    "cat": "politica-italiana"
  },
  {
    "name": "Facta",
    "url": "https://www.facta.news/feed.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Pagella Politica",
    "url": "https://pagellapolitica.it/feed.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Valigia Blu",
    "url": "https://www.valigiablu.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Internazionale",
    "url": "https://www.internazionale.it/subscribe/opinioni/",
    "cat": "geopolitica"
  },
  {
    "name": "Limes",
    "url": "https://www.limesonline.com/rss",
    "cat": "geopolitica"
  },
  {
    "name": "BBC World",
    "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "The Economist",
    "url": "https://www.economist.com/international/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "El Pais",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "cat": "geopolitica"
  },
  {
    "name": "Al Jazeera",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "cat": "conflitti"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/rss/index.xml",
    "cat": "ai"
  },
  {
    "name": "Wired IT",
    "url": "https://www.wired.it/feed/rss",
    "cat": "ai"
  },
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Post Tech",
    "url": "https://www.ilpost.it/tecnologia/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Sole 24 Ore",
    "url": "https://www.ilsole24ore.com/rss/economia.xml",
    "cat": "economia-tech"
  },
  {
    "name": "Bloomberg Tech",
    "url": "https://feeds.bloomberg.com/technology/news.rss",
    "cat": "economia-tech"
  },
  {
    "name": "Financial Times",
    "url": "https://www.ft.com/rss/home",
    "cat": "economia-tech"
  },
  {
    "name": "The Economist Ec",
    "url": "https://www.economist.com/business/rss.xml",
    "cat": "economia-tech"
  }
];

const NEWS = [
  {
    id: "7d1fff8a720284926633",
    cat: "politica-italiana",
    title: "Bologna ricorda la strage, Mattarella: 'Strategia neofascista'. Meloni: 'Fu terrorismo feroce'",
    summary: "Corteo nel capoluogo emiliano, sfilano anche i parenti di Fakir insieme al sindaco Lepore e ai migliaia di persone",
    body: "Corteo nel capoluogo emiliano, sfilano anche i parenti di Fakir insieme al sindaco Lepore e ai migliaia di persone",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/cronaca/2026/08/02/bologna-ricorda-la-strage-mattarella-strategia-neofascista.-meloni-fu-terrorismo-feroce_d040c4ef-2d4e-429b-beee-e39cc1efe837.html",
    time: "59 min fa",
    pub_ts: 1785669283,
    published_at: "2026-08-02T11:14:43+00:00",
    language: "it",
    score: 3,
  },
  {
    id: "0480c118a19727b2a2ae",
    cat: "politica-italiana",
    title: "Terremoto ai Campi Flegrei, riaperto il porto di Pozzuoli",
    summary: "Ancora chiuso il mercato ittico, dopo scossa ingenti danni per il commercio",
    body: "Ancora chiuso il mercato ittico, dopo scossa ingenti danni per il commercio",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/cronaca/2026/08/02/terremoto-ai-campi-flegrei-riaperto-il-porto-di-pozzuoli_aae7adb6-4ca6-43e9-9ec7-e96237f7651b.html",
    time: "1 ora fa",
    pub_ts: 1785667619,
    published_at: "2026-08-02T10:46:59+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "463bda35079c3d9f1092",
    cat: "politica-italiana",
    title: "Aereo si schianta in Perù, 'aveva problemi meccanici'. Distrutte due famiglie italiane",
    summary: "Sette vittime, erano tutti brianzoli. Il cordoglio di Meloni e Attilio Fontana",
    body: "Sette vittime, erano tutti brianzoli. Il cordoglio di Meloni e Attilio Fontana",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/cronaca/2026/08/01/aperta-la-camera-ardente-di-don-mazzi-nella-sede-di-exodus_ac5fcd28-454f-400d-a83f-3bc9a51c3f14.html",
    time: "17 ore fa",
    pub_ts: 1785610739,
    published_at: "2026-08-01T18:58:59+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "721dafec16c4ba7158f1",
    cat: "politica-italiana",
    title: "Perché la Camera non ha ancora deciso che fare sulle chat di Delmastro",
    summary: "L’arrivo di nuovi documenti dalla Procura di Roma ha fatto slittare il voto e ha generato uno stallo tra maggioranza e opposizioni",
    body: "L’arrivo di nuovi documenti dalla Procura di Roma ha fatto slittare il voto e ha generato uno stallo tra maggioranza e opposizioni",
    source: "Pagella Politica",
    url: "https://pagellapolitica.it/articoli/camera-decisione-chat-delmastro",
    time: "2 giorni fa",
    pub_ts: 1785494181,
    published_at: "2026-07-31T10:36:21+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "d73e27064ad956bffca9",
    cat: "politica-italiana",
    title: "Perché l’UE vuole cambiare le regole per le imprese inquinanti",
    summary: "La Commissione europea ha presentato una revisione del sistema che fissa un prezzo alle emissioni industriali e che arriva dopo mesi di pressioni da parte di alcuni Stati, tra cui l’Italia",
    body: "La Commissione europea ha presentato una revisione del sistema che fissa un prezzo alle emissioni industriali e che arriva dopo mesi di pressioni da parte di alcuni Stati, tra cui l’Italia",
    source: "Pagella Politica",
    url: "https://pagellapolitica.it/articoli/ue-cambiare-regole-imprese-inquinanti",
    time: "2 giorni fa",
    pub_ts: 1785488272,
    published_at: "2026-07-31T08:57:52+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "7a818a878cb27d4ca768",
    cat: "politica-italiana",
    title: "Ha senso sospendere l’accordo di Schengen con la Spagna?",
    summary: "L’idea è stata lanciata dal governo dopo le migliaia di migranti arrivati a Ceuta. L’Italia però deve rispettare vincoli precisi e la soluzione potrebbe essere inutile",
    body: "L’idea è stata lanciata dal governo dopo le migliaia di migranti arrivati a Ceuta. L’Italia però deve rispettare vincoli precisi e la soluzione potrebbe essere inutile",
    source: "Pagella Politica",
    url: "https://pagellapolitica.it/articoli/migranti-spagna-accordo-schengen",
    time: "2 giorni fa",
    pub_ts: 1785485498,
    published_at: "2026-07-31T08:11:38+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "d40a5be0d9b80f453baa",
    cat: "politica-italiana",
    title: "Sessualizzare le atlete donne, ma con l’IA",
    summary: "Le atlete generate con l’IA sono diventate virali, tra ritorno economico e sessualizzazione dei corpi",
    body: "Le atlete generate con l’IA sono diventate virali, tra ritorno economico e sessualizzazione dei corpi",
    source: "Facta",
    url: "https://www.facta.news/articoli/atlete-sessualizzate-ia",
    time: "2 giorni fa",
    pub_ts: 1785477370,
    published_at: "2026-07-31T05:56:10+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "0cd669b8ab48af3d5836",
    cat: "politica-italiana",
    title: "Come la Lettonia sta diventando la terra promessa dei misogini online",
    summary: "Una storia virale (falsa) sta trasformando il Paese baltico nel nuovo paradiso dei Passport Bro, i nomadi digitali della manosfera alla ricerca di mogli dai valori tradizionali",
    body: "Una storia virale (falsa) sta trasformando il Paese baltico nel nuovo paradiso dei Passport Bro, i nomadi digitali della manosfera alla ricerca di mogli dai valori tradizionali",
    source: "Facta",
    url: "https://www.facta.news/articoli/lettonia-terra-promessa-misogini-online",
    time: "3 giorni fa",
    pub_ts: 1785410286,
    published_at: "2026-07-30T11:18:06+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "362f236590721f675f51",
    cat: "geopolitica",
    title: "Trump dice que suspende los ataques contra Irán a la espera de un acuerdo rápido",
    summary: "El presidente de EE UU asegura haber tomado la decisión a petición de Teherán y de otros países de Oriente Próximo",
    body: "Nuevo bandazo en la guerra de Irán. Tras unos días en los que Washington había vuelto a golpear con fuerza a la República Islámica, el presidente de Estados Unidos, Donald Trump, ha anunciado que congela los ataques para tratar de buscar un acuerdo. En esta ocasión, asegura que lo hace a petición de Teherán y de otros países de la región que no especifica. Y que cuenta con el beneplácito de Israel.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-08-02/donald-trump-dice-que-suspende-los-ataques-contra-iran-a-la-espera-de-un-acuerdo-rapido.html",
    time: "2 ore fa",
    pub_ts: 1785662090,
    published_at: "2026-08-02T09:14:50+00:00",
    language: "es",
    score: 1,
  },
  {
    id: "943b27df6860a3a2303d",
    cat: "geopolitica",
    title: "Perché è così difficile girare l’Europa in treno",
    summary: "La rete e i servizi ferroviari del continente sono al di sotto delle aspettative dei cittadini e non all’altezza di un continente unito",
    body: "La rete e i servizi ferroviari del continente sono al di sotto delle aspettative dei cittadini e non all’altezza di un continente unito",
    source: "Internazionale",
    url: "https://www.internazionale.it/notizie/2026/08/02/treni-europa",
    time: "8 ore fa",
    pub_ts: 1785642242,
    published_at: "2026-08-02T03:44:02+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "a0d1cd353bfca5052b77",
    cat: "geopolitica",
    title: "La crisis de Ceuta alinea a la derecha europea contra Sánchez",
    summary: "El presidente español, cada vez más solo en Europa, acusa a sus socios de falta de solidaridad, mientras PP y Vox avivan la batalla por la inmigración",
    body: "Un nuevo fantasma recorre Europa y esta vez se llama inmigración. Sobre él cabalga la rampante derechización del continente. Y ante él, Pedro Sánchez, el único socialdemócrata al mando de uno de los grandes países de los 27, se ve cada vez más solo, como ha evidenciado la crisis de Ceuta con sus imágenes de una oleada humana que han impresionado a todo el planeta . Pero, muy en su estilo, el presidente español no rehúye la batalla.\n\nComo prueba, la carta que envió este sábado a Bruselas denunciando el “egoísmo” de algunos de sus socios europeos. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-08-02/la-crisis-de-ceuta-alinea-a-la-derecha-europea-contra-sanchez.html",
    time: "8 ore fa",
    pub_ts: 1785641401,
    published_at: "2026-08-02T03:30:01+00:00",
    language: "es",
    score: 1,
  },
  {
    id: "1a724f945effc5a518e5",
    cat: "geopolitica",
    title: "Trump asegura que las conversaciones con Irán se reanudarán este lunes",
    summary: "El presidente de EE UU trata de rebajar el enfrentamiento de los últimos días para volver a un alto el fuego",
    body: "El presidente de Estados Unidos, Donald Trump, ha dicho a última hora del domingo que las conversaciones con Irán se reanudarán este lunes. Ha hecho estas declaraciones desde el avión presidencial rumbo a Egipto, y tras mantener conversaciones con los líderes de Arabia Saudí, Emiratos Árabes y Qatar, que, según ha dicho, le pidieron “cancaelar” los ataques a la República Islámica porque creen que hay espacio para el acuerdo.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-08-02/la-doble-vara-de-medir-de-trump-de-la-complacencia-con-marruecos-a-la-incomodidad-con-espana.html",
    time: "8 ore fa",
    pub_ts: 1785641401,
    published_at: "2026-08-02T03:30:01+00:00",
    language: "es",
    score: 1,
  },
  {
    id: "3bfea721737408d2f0be",
    cat: "geopolitica",
    title: "Rivoluzione permanente",
    summary: "Ogni volta che vedo un programma di teatro ambientato nelle strade di Roma, penso a come il socialismo potrebbe arrivare in città semplicemente non smontando i palchi dopo gli spettacoli",
    body: "Ogni volta che vedo un programma di teatro ambientato nelle strade di Roma, penso a come il socialismo potrebbe arrivare in città semplicemente non smontando i palchi dopo gli spettacoli",
    source: "Internazionale",
    url: "https://www.internazionale.it/opinione/christian-raimo/2026/08/01/rivoluzione-permanente-teatro",
    time: "1 giorno fa",
    pub_ts: 1785556502,
    published_at: "2026-08-01T03:55:02+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "5811cb247bbb863126fa",
    cat: "geopolitica",
    title: "Le domande e i miti sbagliati su Elena di Troia",
    summary: "Per molti la scelta di Lupita Nyong’o per il ruolo di Elena nell’Odissea di Christopher Nolan è un tradimento dell’opera di Omero. Ma non è affatto così",
    body: "Per molti la scelta di Lupita Nyong’o per il ruolo di Elena nell’Odissea di Christopher Nolan è un tradimento dell’opera di Omero. Ma non è affatto così",
    source: "Internazionale",
    url: "https://www.internazionale.it/opinione/asha-salim/2026/08/01/elena-troia-odissea-nolan",
    time: "1 giorno fa",
    pub_ts: 1785555841,
    published_at: "2026-08-01T03:44:01+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "d1cb3ff54dbe683cdf54",
    cat: "geopolitica",
    title: "Alle urne, Israele farà i conti con i suoi errori strategici",
    summary: "Alle elezioni di ottobre gli israeliani giudicheranno la lunga èra Netanyahu e la strategia nazionale perseguita dal paese. Il 7 ottobre è la punta dell’iceberg del fallimento di una dottrina di sicurezza inadeguata. Come il rafforzamento di Hamas e degli agenti di prossimità iraniani negli ultimi anni è stato sottovalutato.",
    body: "Alle elezioni di ottobre gli israeliani giudicheranno la lunga èra Netanyahu e la strategia nazionale perseguita dal paese. Il 7 ottobre è la punta dell’iceberg del fallimento di una dottrina di sicurezza inadeguata. Come il rafforzamento di Hamas e degli agenti di prossimità iraniani negli ultimi anni è stato sottovalutato.",
    source: "Limes",
    url: "https://www.limesonline.com/articoli/israele-netanyahu-verso-le-elezioni-di-ottobre-dopo-anni-di-errori-strategici-minacce-iran-hezbollah-huthi-7-ottobre-gaza-22449405",
    time: "2 giorni fa",
    pub_ts: 1785482100,
    published_at: "2026-07-31T07:15:00+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "58bc250dbe0aea4e1874",
    cat: "conflitti",
    title: "Trump: 'Ritiro l'attacco su richiesta di Teheran' ma l'Iran replica: 'Hormuz resta chiuso'",
    summary: "Il presidente Usa: 'Ora rapido accordo su Hormuz e stop minaccia nucleare'",
    body: "Il presidente Usa: 'Ora rapido accordo su Hormuz e stop minaccia nucleare'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/08/02/trump-ritiro-lattacco-sulliran-su-richiesta-di-teheran-e-altri-paesi_9627b960-bbbb-43e9-891a-e77a10e8b09e.html",
    time: "54 min fa",
    pub_ts: 1785669602,
    published_at: "2026-08-02T11:20:02+00:00",
    language: "it",
    score: 2,
  },
  {
    id: "bfe571f15ed5e72d87a4",
    cat: "conflitti",
    title: "From Sudan to Spain: Between war and home | Al Jazeera Originals",
    summary: "A young Sudanese refugee rebuilds his life in Spain while war keeps him from the family he left behind.",
    body: "A young Sudanese refugee rebuilds his life in Spain while war keeps him from the family he left behind.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/al-jazeera-documentaries/2026/8/2/aje-onl-aj_or_sdn_war-020826?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1785668833,
    published_at: "2026-08-02T11:07:13+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "5faca102c10bc54e6297",
    cat: "conflitti",
    title: "Israeli soldiers jailed over Sde Teiman walkout",
    summary: "Fourteen Israeli soldiers have been sentenced to military prison after leading an unauthorised walkout from Sde Teiman.",
    body: "Fourteen Israeli soldiers have been sentenced to military prison after leading an unauthorised walkout from Sde Teiman.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/8/2/israeli-soldiers-jailed-over-sde-teiman-walkout?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1785666692,
    published_at: "2026-08-02T10:31:32+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "5f417ba8762b34df3c8c",
    cat: "conflitti",
    title: "Sui pattini tra le rovine di Gaza: quando lo sport diventa una fuga dalla guerra",
    summary: "A Khan Yunis giovani palestinesi si allenano tra gli edifici distrutti",
    body: "A Khan Yunis giovani palestinesi si allenano tra gli edifici distrutti",
    source: "ANSA",
    url: "https://www.ansa.it/sito/videogallery/mondo/2026/08/02/sui-pattini-tra-le-rovine-di-gaza-quando-lo-sport-diventa-una-fuga_c6537088-2d76-4229-844e-b707986367ef.html",
    time: "3 ore fa",
    pub_ts: 1785661709,
    published_at: "2026-08-02T09:08:29+00:00",
    language: "it",
    score: 2,
  },
  {
    id: "4b04f5d801dc8af598a6",
    cat: "conflitti",
    title: "Raid israeliani su Gaza nella notte, 9 morti tra cui 3 bambini",
    summary: "La difesa civile palestinese: 'Ucciso anche un bambino vicino Khan Younis'",
    body: "La difesa civile palestinese: 'Ucciso anche un bambino vicino Khan Younis'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/08/02/raid-israeliani-su-gaza-nella-notte-almeno-otto-morti_9311cfac-6dbd-4645-9a85-97656b2e564e.html",
    time: "3 ore fa",
    pub_ts: 1785661511,
    published_at: "2026-08-02T09:05:11+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "4186d58d9d1db4436ae7",
    cat: "conflitti",
    title: "Iran war live: Iranian foreign ministry says no current talks with US",
    summary: "US President Donald Trump says an agreement with Iran is imminent, with negotiations set to begin on Monday.",
    body: "US President Donald Trump says an agreement with Iran is imminent, with negotiations set to begin on Monday.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/features/2026/8/2/gaza-students-overcome-israels-genocide-to-celebrate-tawjihi-results?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1785648424,
    published_at: "2026-08-02T05:27:04+00:00",
    language: "en",
    score: 2,
  },
  {
    id: "b8db47da6ab81aa76170",
    cat: "conflitti",
    title: "Bowen: Plan for Hamas to disarm faces big obstacles, yet it offers rare hope for Gaza",
    summary: "The realities of politics, war, zero trust, the deaths of thousands and the destruction of Gaza will make any agreement very complicated.",
    body: "The realities of politics, war, zero trust, the deaths of thousands and the destruction of Gaza will make any agreement very complicated.",
    source: "BBC World",
    url: "https://www.bbc.co.uk/news/articles/c2dkje4p4klo?at_medium=RSS&at_campaign=rss",
    time: "1 giorno fa",
    pub_ts: 1785511111,
    published_at: "2026-07-31T15:18:31+00:00",
    language: "en",
    score: 3,
  },
  {
    id: "73bd79365ca086372c91",
    cat: "ai",
    title: "AI Act, Garante Privacy 'rafforzare le tutele per i dati biometrici'",
    summary: "L'Autorità individua alcuni profili da integrare nello schema di decreto legislativo",
    body: "L'Autorità individua alcuni profili da integrare nello schema di decreto legislativo",
    source: "ANSA",
    url: "https://www.ansa.it/canale_tecnologia/notizie/tecnologia/2026/07/29/ai-act-garante-privacy-rafforzare-le-tutele-per-i-dati-biometrici_ca1f12b2-63fd-4948-b992-1f5e154752a1.html",
    time: "2 ore fa",
    pub_ts: 1785662451,
    published_at: "2026-08-02T09:20:51+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "87fcebaf844d84a01440",
    cat: "ai",
    title: "IA fuori controllo, anche i modelli Claude di Anthropic hanno violato sistemi esterni",
    summary: "Durante i test, alcune versioni delle IA hanno attaccato infrastrutture reali",
    body: "Durante i test, alcune versioni delle IA hanno attaccato infrastrutture reali",
    source: "ANSA",
    url: "https://www.ansa.it/canale_tecnologia/notizie/future_tech/2026/07/31/ia-fuori-controllo-anche-i-modelli-claude-di-anthropic-hanno-violato-sistemi-esterni_80c316e1-b8da-420f-af7f-17cade551cb4.html",
    time: "18 ore fa",
    pub_ts: 1785604607,
    published_at: "2026-08-01T17:16:47+00:00",
    language: "it",
    score: 2,
  },
  {
    id: "02523526d0cd7f93c944",
    cat: "ai",
    title: "Sam Altman is still making the case for parenting via ChatGPT",
    summary: "OpenAI's CEO seemed excited to share a \"cool use case\" for parents.",
    body: "OpenAI's CEO seemed excited to share a \"cool use case\" for parents.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/08/01/sam-altman-is-still-making-the-case-for-parenting-via-chatgpt",
    time: "19 ore fa",
    pub_ts: 1785604054,
    published_at: "2026-08-01T17:07:34+00:00",
    language: "en",
    score: 2,
  },
  {
    id: "1be96cfc2a27da3f46b3",
    cat: "ai",
    title: "Trump blames Tim Walz for water hacks even though it’s probably Iran",
    summary: "The FBI, the EPA, and the Cybersecurity and Infrastructure Security Agency (CISA) have stopped short of officially blaming Iran for a spate of cyberattacks on Minnesota's water systems, but consensus is that Iran is likely behind them. That, of course, hasn't stopped Donald Trump from sharing his own theory - that Governor Tim Walz is",
    body: "Donald Trump speaks during the House Republican Party member retreat. | Image: Mandel NGAN / AFP via Getty Images The FBI, the EPA, and the Cybersecurity and Infrastructure Security Agency ( CISA ) have stopped short of officially blaming Iran for a spate of cyberattacks on Minnesota's water systems, but consensus is that Iran is likely behind them. That, of course, hasn't stopped Donald Trump from sharing his own theory - that Governor Tim Walz is to blame and telling reporters that \"I don't think there was an Iranian cyberattack.\" Trump's comments come shortly after the FBI issued a warning that the cyberattacks on American infrastructure were spreading to other states.\n\nIn Minnesota alone, at least 30 community water systems had been targeted in what a …",
    source: "The Verge",
    url: "https://www.theverge.com/policy/974197/trump-tim-walz-minnesota-water-hacks-iran",
    time: "20 ore fa",
    pub_ts: 1785597815,
    published_at: "2026-08-01T15:23:35+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "36dabcd3de34bd7da2b5",
    cat: "ai",
    title: "OpenAI reportedly finds evidence that more of its agents ran amok",
    summary: "OpenAI has reportedly found evidence of additional agent misbehavior as it looks into the incident that occurred with Hugging Face.",
    body: "OpenAI has reportedly found evidence of additional agent misbehavior as it looks into the incident that occurred with Hugging Face.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/31/openai-reportedly-finds-evidence-that-more-of-its-agents-ran-amok",
    time: "1 giorno fa",
    pub_ts: 1785538046,
    published_at: "2026-07-31T22:47:26+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "104a699a07434f04c7a8",
    cat: "ai",
    title: "Rivian spinoff Also to start delivering e-bikes after months of delays",
    summary: "Also has big plans beyond the TM-B. The startup mostly refers to itself as a \"vehicle\" company and has plans to make four-wheel pedal-assist cargo vehicles for Amazon.",
    body: "Also has big plans beyond the TM-B. The startup mostly refers to itself as a \"vehicle\" company and has plans to make four-wheel pedal-assist cargo vehicles for Amazon.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/31/rivian-spinoff-also-to-start-delivering-e-bikes-after-months-of-delays",
    time: "1 giorno fa",
    pub_ts: 1785535208,
    published_at: "2026-07-31T22:00:08+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "ff5eb5aed7cd25f21209",
    cat: "ai",
    title: "Che cos’è questa storia dei libri distrutti dalle aziende dei chatbot IA",
    summary: "Per addestrare Claude, Anthropic ha scansionato milioni di libri tagliandone il dorso per velocizzare il processo di digitalizzazione",
    body: "Per addestrare Claude, Anthropic ha scansionato milioni di libri tagliandone il dorso per velocizzare il processo di digitalizzazione",
    source: "Facta",
    url: "https://www.facta.news/articoli/libri-distrutti-dalle-aziende-chatbot-ia",
    time: "1 giorno fa",
    pub_ts: 1785500813,
    published_at: "2026-07-31T12:26:53+00:00",
    language: "it",
    score: 2,
  },
  {
    id: "30987f91bbf099faa890",
    cat: "ai",
    title: "Davvero il governo vuole istituire una sorta di “Grande fratello”?",
    summary: "Lo sostengono le opposizioni per un provvedimento su intelligenza artificiale e attività di polizia, che autorizza in alcuni casi l’uso del riconoscimento facciale",
    body: "Lo sostengono le opposizioni per un provvedimento su intelligenza artificiale e attività di polizia, che autorizza in alcuni casi l’uso del riconoscimento facciale",
    source: "Pagella Politica",
    url: "https://pagellapolitica.it/articoli/riconoscimento-facciale-governo-meloni",
    time: "3 giorni fa",
    pub_ts: 1785408980,
    published_at: "2026-07-30T10:56:20+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "daff38841c270540b654",
    cat: "economia-tech",
    title: "Whatever happened to prudence?",
    summary: "Governments have stopped correcting budget deficits but — so far — bond markets have let them",
    body: "Governments have stopped correcting budget deficits but — so far — bond markets have let them",
    source: "Financial Times",
    url: "https://www.ft.com/content/3f651fa0-3362-4a16-9ac1-992291c5f68a?syn-25a6b1a6=1",
    time: "2 ore fa",
    pub_ts: 1785664805,
    published_at: "2026-08-02T10:00:05+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "0f63cacce1a22e926949",
    cat: "economia-tech",
    title: "Wall Street learns to love blockchain",
    summary: "Financial companies hope to modernise markets with the technology but systemic risks remain",
    body: "Financial companies hope to modernise markets with the technology but systemic risks remain",
    source: "Financial Times",
    url: "https://www.ft.com/content/7600731b-4f7f-4d38-a478-3196c565a880?syn-25a6b1a6=1",
    time: "4 ore fa",
    pub_ts: 1785729604,
    tags: [],
  },
  {
    id: 20,
    cat: "economia-tech",
    title: "China’s Wu Vows Further Expansion of Market Links to Hong Kong",
    summary: "China is working closely with Hong Kong authorities to expand the Stock Connect cross-border trading link by adding yuan-denominated stock counters and real estate investment trusts, according China Securities Regulatory Commission Chairman Wu Qing.",
    body: "China is working closely with Hong Kong authorities to expand the Stock Connect cross-border trading link by adding yuan-denominated stock counters and real estate investment trusts, according China Securities Regulatory Commission Chairman Wu Qing.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-08-01/zepto-turns-to-private-funding-with-ipo-plans-on-hold-for-now",
    time: "20 ore fa",
    pub_ts: 1785597455,
    published_at: "2026-08-01T15:17:35+00:00",
    language: "en",
    score: 1,
  },
  {
    id: "5613ab8d3696c407ca07",
    cat: "economia-tech",
    title: "Stellantis, il mercato italiano guida la ripresa, corre il marchio Fiat",
    summary: "Sul mercato domestico, un quarto delle immatricolazioni in più registrate in Europa nel primo semestre dell’anno - I nuovi modelli Fiat Grande Panda e Citroen C3 trainano i volumi",
    body: "Sul mercato domestico, un quarto delle immatricolazioni in più registrate in Europa nel primo semestre dell’anno - I nuovi modelli Fiat Grande Panda e Citroen C3 trainano i volumi",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/stellantis-mercato-italiano-guida-ripresa-corre-marchio-fiat-AJ1T7DY",
    time: "1 giorno fa",
    pub_ts: 1785556921,
    published_at: "2026-08-01T04:02:01+00:00",
    language: "it",
    score: 1,
  },
  {
    id: "4b1e2ee386a0ee8eb05b",
    cat: "economia-tech",
    title: "La complicata vita di una banconota",
    summary: "Abbiamo visitato il complesso in cui Banca d’Italia e BCE stampano le banconote destinate a tutta l’Eurozona, per capire come si fanno e come funziona il sistema che ci sta intorno",
    body: "Abbiamo visitato il complesso in cui Banca d’Italia e BCE stampano le banconote destinate a tutta l’Eurozona, per capire come si fanno e come funziona il sistema che ci sta intorno",
    source: "Pagella Politica",
    url: "https://pagellapolitica.it/articoli/complicata-vita-banconota-conti-in-tasca",
    time: "3 giorni fa",
    pub_ts: 1785409899,
    published_at: "2026-07-30T11:11:39+00:00",
    language: "it",
    score: 1,
  },
];
