// Generato automaticamente il 2026-07-08 04:19 UTC da scripts/fetch_news.py
// NON modificare manualmente: viene sovrascritto ogni ora dalla GitHub Action.
var NEWS_TIMESTAMP = 1783484366;

const RSS_SOURCES = [
  {
    "name": "ANSA",
    "url": "https://www.ansa.it/sito/ansait_rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Corriere",
    "url": "https://xml2.corrieredellasera.it/rss/homepage.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Il Post",
    "url": "https://www.ilpost.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Sky TG24",
    "url": "https://tg24.sky.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "AGI",
    "url": "https://www.agi.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Pagella Politica",
    "url": "https://pagellapolitica.it/feed",
    "cat": "politica-italiana"
  },
  {
    "name": "Facta",
    "url": "https://facta.news/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Valigia Blu",
    "url": "https://www.valigiablu.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Limes",
    "url": "https://www.limesonline.com/feed",
    "cat": "geopolitica"
  },
  {
    "name": "Internazionale",
    "url": "https://www.internazionale.it/feed/tutto",
    "cat": "geopolitica"
  },
  {
    "name": "BBC World",
    "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "AP",
    "url": "https://apnews.com/hub/world-news?output=rss",
    "cat": "geopolitica"
  },
  {
    "name": "The Economist",
    "url": "https://www.economist.com/international/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "El Pais",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "cat": "geopolitica"
  },
  {
    "name": "Reuters",
    "url": "https://feeds.reuters.com/reuters/worldNews",
    "cat": "conflitti"
  },
  {
    "name": "Al Jazeera",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "cat": "conflitti"
  },
  {
    "name": "AP conflitti",
    "url": "https://apnews.com/hub/wars-and-conflicts?output=rss",
    "cat": "conflitti"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/rss/index.xml",
    "cat": "ai"
  },
  {
    "name": "Wired IT",
    "url": "https://www.wired.it/feed/rss",
    "cat": "ai"
  },
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Post Tech",
    "url": "https://www.ilpost.it/tecnologia/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Sole 24 Ore",
    "url": "https://www.ilsole24ore.com/rss/economia.xml",
    "cat": "economia-tech"
  },
  {
    "name": "Bloomberg Tech",
    "url": "https://feeds.bloomberg.com/technology/news.rss",
    "cat": "economia-tech"
  },
  {
    "name": "Financial Times",
    "url": "https://www.ft.com/rss/home",
    "cat": "economia-tech"
  },
  {
    "name": "The Economist Ec",
    "url": "https://www.economist.com/business/rss.xml",
    "cat": "economia-tech"
  }
];

const NEWS = [
  {
    id: 1,
    cat: "politica-italiana",
    title: "A Manhattan si teme il crollo parziale di un grattacielo, area transennata e traffico in tilt",
    summary: "Il sindaco di New York Mamdani: 'Due colonne piegate, ci sono crepe e cedimenti'",
    body: "Il sindaco di New York Mamdani: 'Due colonne piegate, ci sono crepe e cedimenti'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/07/08/timore-di-un-crollo-parziale-di-un-grattacielo-a-new-york-area-transennata_0087c209-a918-47b5-a58b-56b944ea266c.html",
    time: "3 ore fa",
    pub_ts: 1783473234,
    tags: [],
  },
  {
    id: 2,
    cat: "politica-italiana",
    title: "Trump: 'Deluso dalla Nato, Meloni mi piace ma non ci ha aiutato'. La premier: 'Rapporti cordiali'",
    summary: "Il presidente Usa si dice 'deluso dalla Nato' e attacca anche Francia, Regno Unito e Germania: 'Si sono sfilati'. E rilancia sulla Groenlandia",
    body: "Il presidente Usa si dice 'deluso dalla Nato' e attacca anche Francia, Regno Unito e Germania: 'Si sono sfilati'. E rilancia sulla Groenlandia",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/07/07/trump-deluso-dalla-nato-meloni-mi-piace-ma-non-ci-ha-aiutato.-la-premier-rapporti_f8d739d7-37c6-4d0f-bd18-f93fbe6e5309.html",
    time: "6 ore fa",
    pub_ts: 1783459705,
    tags: [],
  },
  {
    id: 3,
    cat: "politica-italiana",
    title: "Le Pen condannata ma non molla: 'Mi candido all'Eliseo, e senza braccialetto'",
    summary: "Pena ridotta, fa ricorso per 'sospendere la misura'. 'Ticket con Bardella premier'",
    body: "Pena ridotta, fa ricorso per 'sospendere la misura'. 'Ticket con Bardella premier'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/07/07/marine-le-pen-dichiarata-colpevole-ineleggibilita-gia-scontata-potrebbe-candidarsi_66bdab19-4186-400b-9b04-d685cd71ef71.html",
    time: "9 ore fa",
    pub_ts: 1783450849,
    tags: [],
  },
  {
    id: 4,
    cat: "politica-italiana",
    title: "Cocente sconfitta legale contro il Mail, l'ira del principe Harry",
    summary: "'Insabbiamento'. Inizia male la visita del duca a Londra, per ora nessun incontro col re",
    body: "'Insabbiamento'. Inizia male la visita del duca a Londra, per ora nessun incontro col re",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/07/07/harry-a-londra-per-una-visita-di-5-giorni-nel-regno-unito.-lui_ac8dbe8d-6e5b-4969-be85-fb80c3f954f2.html",
    time: "9 ore fa",
    pub_ts: 1783448933,
    tags: [],
  },
  {
    id: 5,
    cat: "politica-italiana",
    title: "Ammissibile il conflitto di poteri per Bartolozzi sul caso Almasri",
    summary: "La Consulta accoglie la richiesta della Camera nei confronti Tribunale ministri. Udienza in autunno",
    body: "La Consulta accoglie la richiesta della Camera nei confronti Tribunale ministri. Udienza in autunno",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/cronaca/2026/07/07/ammissibile-il-conflitto-di-poteri-per-bartolozzi-sul-caso-almasri_8e513e68-26ad-40fa-98f4-2d36ee4e575d.html",
    time: "11 ore fa",
    pub_ts: 1783443623,
    tags: [],
  },
  {
    id: 6,
    cat: "politica-italiana",
    title: "Sì dell'Eurocamera all'indagine sul partito di estrema destra Esn",
    summary: "Il voto si è tenuto a scrutinio segreto",
    body: "Il voto si è tenuto a scrutinio segreto",
    source: "ANSA",
    url: "https://www.ansa.it/europa/notizie/rubriche/voceeurodeputati/2026/07/07/-si-delleurocamera-a-indagine-sul-partito-di-estrema-destra-esn-_d100e4c6-9313-40d2-9878-266ab57715da.html",
    time: "13 ore fa",
    pub_ts: 1783434541,
    tags: [],
  },
  {
    id: 7,
    cat: "geopolitica",
    title: "US launches strikes on Iran after tankers hit in Strait of Hormuz",
    summary: "The US says the strikes are intended to impose \"heavy costs\", while Iran warns it will \"take decisive measures\" in response.",
    body: "The US says the strikes are intended to impose \"heavy costs\", while Iran warns it will \"take decisive measures\" in response.",
    source: "BBC World",
    url: "https://www.bbc.co.uk/news/articles/cwykq59jwpvo?at_medium=RSS&at_campaign=rss",
    time: "poco fa",
    pub_ts: 1783484306,
    tags: [],
  },
  {
    id: 8,
    cat: "geopolitica",
    title: "La FIFA tiene unas normas, pero si llama Trump, tiene otras",
    summary: "La suspensión de una sanción a un jugador estadounidense tras la intervención del presidente de EE UU cuestiona la independencia del organismo y agita el torneo",
    body: "La decisión de la FIFA de suspender la sanción a un delantero estadounidense expulsado en un partido del Mundial ha desatado una tormenta sin precedentes en plena competición. La tarjeta roja implicaba, según el reglamento, un partido automático de suspensión, pero el organismo optó por paralizar la sanción mediante una medida cautelar, permitiendo al jugador disputar el siguiente encuentro. La resolución llegó después de que el presidente de Estados Unidos, Donald Trump, contactara con el máximo dirigente de la FIFA para pedir una revisión del caso.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/podcasts/hoy-en-el-pais/2026-07-08/la-fifa-tiene-unas-normas-pero-si-llama-trump-tiene-otras.html",
    time: "34 min fa",
    pub_ts: 1783482301,
    tags: [],
  },
  {
    id: 9,
    cat: "geopolitica",
    title: "Sí a Londres, pero no a Ankara: expertos ven en la decisión sobre Begoña Gómez un “disparate” condicionado por la prohibición inicial de Peinado",
    summary: "Los juristas consultados no aprecian “riesgo de fuga” en la mujer del presidente del Gobierno, pero entienden que el juez sustituto no tenía mucho margen",
    body: "Una de cal y otra de arena. Así resolvió el juez instructor Antonio Viejo la petición de Begoña Gómez para que le autorizara a viajar en estos días, primero a Ankara, para acompañar a su marido, Pedro Sánchez, a la Cumbre de la OTAN, y después a Londres, para asistir a la graduación de su hija. Negó lo primero y concedió lo segundo, en una decisión in extremis que, en realidad, no le correspondía: simplemente es el sustituto de quien a su vez sustituye al juez titular del caso, Juan Carlos Peinado, y ambos estaban de libranza.\n\nLos expertos consultados por EL PAÍS creen que esta interinidad tan acusada ha influido en este fallo salomónico, si bien la mayoría parte de la premisa de que considerar que la mujer del presidente del Gobierno puede fugarse es “un disparate”. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-08/si-a-londres-pero-no-a-ankara-expertos-ven-en-la-decision-sobre-begona-gomez-un-disparate-condicionado-por-la-prohibicion-inicial-de-peinado.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 10,
    cat: "geopolitica",
    title: "Miguel Ángel Rodríguez y la ducha de después",
    summary: "Se busca agitar un debate sobre el aborto que no existe en la sociedad española y solo interesa a una minoría de fanáticos religiosos",
    body: "Como bien sabía el quisquilloso de Freud, nos damos a conocer más en los descuidos que en las palabras meditadas. Muy meditadas no han sido nunca las palabras del asesor de la presidenta de Madrid Miguel Ángel Rodríguez , y no merecerá el labrado en mármol el tuit que esputó tras el anuncio de la ley madrileña del concebido no nacido: “Esto significa que, según termina de fecundar, antes de ducharse, lo que tiene la mujer en su vientre es una persona con derechos”.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-08/miguel-angel-rodriguez-y-la-ducha-de-despues.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 11,
    cat: "geopolitica",
    title: "¿Cómo de extremo es este calor? Los datos de una anomalía histórica en Europa",
    summary: "El continente afronta un segundo episodio de temperaturas inusualmente altas después de la oleada de junio, la más severa jamás registrada",
    body: "La embestida de calor que sufrió Europa a finales de junio es uno de los episodios de altas temperaturas más severos de su historia conocida. Se han batido centenares de récords, desde España hasta los Balcanes, y los datos apuntan a más de 4.000 muertes adicionales relacionadas con las altas temperaturas, según las estimaciones que han ofrecido varios países. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/clima-y-medio-ambiente/2026-07-08/como-de-extremo-es-este-calor-los-datos-de-una-anomalia-historica-en-europa.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 12,
    cat: "geopolitica",
    title: "El debate | ¿Funciona adular a Trump?",
    summary: "La imprevisibilidad y el temperamento volcánico del presidente de Estados Unidos desconcierta y preocupa a los líderes que tratan con él y que no aciertan con la mejor estrategia para tratarle como a cualquier otro mandatario internacional",
    body: "La imprevisibilidad y el temperamento volcánico del presidente de Estados Unidos desconcierta y preocupa a los líderes que tratan con él y que no aciertan con la mejor estrategia para tratarle como a cualquier otro mandatario internacional",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-08/el-debate-funciona-adular-a-trump.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 13,
    cat: "geopolitica",
    title: "Milena Busquets, escritora: “Como yo, mi personaje parece amable y desenfadado, pero los dos tenemos un lado oscuro”",
    summary: "La autora publica ‘Mujeres elegantes’, una entretenidísima colección de textos que conjugan travesura y frivolidad con hálito literario, mucho humor y un sentimiento profundo de la existencia",
    body: "Aunque Milena Busquets se confiesa más de literatura francesa que anglosajona es fácil sentirse ante ella como el abrumado Pip de Grandes esperanzas , de Dickens, ante Esther, la guapa muchacha educada por la amargada pero muy rica señorita Havisham para vengarse del sexo masculino. No es que la escritora, que ahora publica Mujeres elegantes (Lumen), te vaya a partir el corazón, al menos de entrada, sino que como el propio Pip en la casa Manor te haces muy consciente de que no estás preparado para el encuentro.\n\n“Con este muchacho, ¡pero si es un rústico!”, recuerdas que decía Esther juzgando al pobre Pip, y te das cuenta de que llevas un polo gastado, unos tejanos baratos y lavados demasiadas veces, con la única concesión al glamour (relativo) de unas Adidas Samba que ya han pateado demasiada calle y que Busquets parece evaluar como un escáner mientras te encoges en el extremo del sillón largo en el que hemos tomado asiento los dos.\n\nElla, Milena, lleva en cambio una exquisita camisa azul que debe de ser una delicia al tacto (dice que no es de su apreciado Dries Van Noten, que al profano le puede sonar a pintor flamenco pretencioso), unos vaqueros que le quedan como a una modelo y, vaya, no las sandalias Birkenstock Boston que elogia en Mujeres elegantes y que forman casi tan parte de su identidad como Cadaqués o el apellido Tusquets −de su madre, la celebre editora y escritora Esther Tusquets−, sino unas bonitas bailarinas.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/cultura/2026-07-08/milena-busquets-escritora-como-yo-mi-personaje-parece-amable-y-desenfadado-pero-los-dos-tenemos-un-lado-oscuro.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 14,
    cat: "geopolitica",
    title: "Los aliados europeos de la OTAN avanzan para cubrir el hueco de EE UU con misiones en el Atlántico Norte y el Artico",
    summary: "Los aliados europeos y Canadá preparan una nueva iniciativa de patrullaje marítimo tras meses de presión de Trump sobre Groenlandia",
    body: "Los aliados europeos y Canadá avanzan para cubrir los agujeros en el paraguas de seguridad del continente que está dejando Estados Unidos. Un grupo de 12 países, entre los que prevé estar España, prepara una nueva misión para reforzar la seguridad marítima en el Atlántico Norte y en el Ártico, según fuentes de la Alianza. La nueva iniciativa, en la que no estarán fuerzas de Washington, llega tras meses de presiones de la Administración de Donald Trump para que Europa asuma más responsabilidad en la organización militar y después de que el presidente estadounidense renovase sus amenazas de tomar Groenlandia —la enorme isla ártica parte del Reino de Dinamarca— en vísperas de una cumbre de la OTAN que contiene la respiración ante la volatilidad del jefe de la Casa Blanca.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-07-08/los-aliados-europeos-de-la-otan-avanzan-para-cubrir-el-hueco-de-ee-uu-con-misiones-en-el-atlantico-norte-y-el-artico.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 15,
    cat: "geopolitica",
    title: "Bardella, el gran reemplazo del RN, se queda en tierra de nadie",
    summary: "El joven presidente del Reagrupamiento Nacional, disparado en las encuestas, representa una evolución en el discurso del partido ultra",
    body: "El joven presidente del Reagrupamiento Nacional, disparado en las encuestas, representa una evolución en el discurso del partido ultra",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-07-08/bardella-el-gran-reemplazo-del-rn-se-queda-en-tierra-de-nadie.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 16,
    cat: "geopolitica",
    title: "La última victoria ideológica de Ayuso: lo que dice (y lo que no) la ley del concebido no nacido",
    summary: "La norma permite que el embrión compute como hijo a efectos de ayudas y el título de familia numerosa, una medida que expertos y oposición consideran un precedente ideológico",
    body: "Una medida que no va en contra de nadie. Una política útil. Un apoyo a la familia. Un impulso a la natalidad. Y, por último, una defensa de la vida. Es como el Partido Popular de Madrid ha descrito su norma estrella, el broche antes de las vacaciones: la ley del concebido no nacido, prometida por Isabel Díaz Ayuso hace siete años, alabada por la ultraderecha ―con quien la presidenta autonómica compite en el discurso natalista―, y criticada en la izquierda, que la considera “claramente ideológica” y alejada de las necesidades reales de los madrileños.\n\nSe aprobó hace menos de una semana y el líder del PP, Alberto Núñez Feijóo, ya ha dicho que, si gobierna, impulsará una ley estatal igual a la de su compañera de partido. El núcleo de la norma: el embrión se reconoce como un miembro de la familia y, en consecuencia, adquiere “beneficios y derechos”. El PP defiende que esta es una ayuda que padres y madres necesitan y la oposición pone el foco en la lectura entre líneas: considerar al feto como a un hijo es el primer paso para un retroceso en los derechos de las mujeres.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/madrid/2026-07-08/la-ultima-victoria-ideologica-de-ayuso-lo-que-dice-y-lo-que-no-la-ley-del-concebido-no-nacido.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 17,
    cat: "geopolitica",
    title: "Vox considera un error electoral el endurecimiento del discurso del PP y lo atribuye a la presión de Aznar y Ayuso",
    summary: "La formación ultra, sorprendida por la facilidad con la que han cerrado el acuerdo de gobierno con Juan Manuel Moreno en Andalucía",
    body: "En la cúpula de Vox hacen un balance positivo de este curso político plagado de retos en forma de citas electorales autonómicas y del reciente engrasamiento de sus relaciones complejas con el PP de Alberto Núñez Feijóo, pero observan con preocupación creciente el futuro de cara a las elecciones generales por la estrategia actual de endurecimiento en su discurso de los populares. Piensan fuentes de la organización ultra que es un error y entienden que el PP debería centrarse en la búsqueda de sus votantes por el centro.\n\nEn Vox achacan el escoramiento a las posiciones más intransigentes de José María Aznar e Isabel Díaz Ayuso y reconocen además su sorpresa por la facilidad del acuerdo de gobierno en Andalucía con el PP de Juan Manuel Moreno. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-08/vox-considera-un-error-electoral-el-endurecimiento-del-discurso-del-pp-y-lo-atribuye-a-la-presion-de-aznar-y-ayuso.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 18,
    cat: "geopolitica",
    title: "Un juez autorizó que la UCO pinchara el teléfono de Barrabés cinco años después de los contratos investigados",
    summary: "La Fiscalía Europea pidió en marzo de 2026 intervenir el móvil del empresario imputado en el ‘caso Begoña Gómez’ para esclarecer si hubo irregularidades",
    body: "El teléfono del empresario Juan Carlos Barrabés ―fundador y presidente del Grupo Barrabés e investigado en la causa contra Begoña Gómez― estuvo pinchado durante dos meses. Agentes de la Unidad Central Operativa (UCO) de la Guardia Civil realizaron escuchas de sus conversaciones entre marzo y abril de 2026 en el marco de la investigación que se sigue en la Fiscalía Europea y que analiza si hubo irregularidades en dos contratos públicos hace cinco años con la entidad de Red.es (que depende del Ministerio de Transformación Digital).\n\nEl magistrado de la Audiencia Nacional Antonio Piña, que actúa como juez de garantías, avaló la “intervención, observación, grabación y escucha” de todas las conversaciones de Barrabés. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-08/un-juez-autorizo-que-la-uco-pinchara-el-telefono-de-barrabes-cinco-anos-despues-de-los-contratos-investigados.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 19,
    cat: "geopolitica",
    title: "Condena a la Seguridad Social por el estrés causado a una funcionaria por la falta de personal en La Palma: “Había violencia en la puerta”",
    summary: "La afectada, a la que el fallo otorga una indemnización de 15.000 euros, denuncia que la imposición de la atención telefónica en la pandemia redujo al mínimo las citas a los vecinos de la isla",
    body: "Sentencia revolucionaria para la protección del personal de la Administración del Estado. El Tribunal Superior de Justicia de Canarias (TSJC) ha condenado al Instituto Nacional de la Seguridad Social (INSS) al considerar que la falta de plantilla en una oficina de atención al público en Santa Cruz de La Palma ha incumplido la normativa de prevención de riesgos. La sentencia revoca un fallo anterior y reconoce que la Administración ha incumplido sus obligaciones en materia de prevención de riesgos laborales en su vertiente psicosocial, “vulnerando el derecho a la vida, integridad física y moral” de una funcionaria, a la que deberá indemnizar con 15.000 euros por daños morales tras tres años de litigio.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-08/condena-a-la-seguridad-social-por-el-estres-causado-a-una-funcionaria-debido-a-la-falta-de-personal-en-la-palma-habia-violencia-en-la-puerta.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 20,
    cat: "geopolitica",
    title: "Una universidad neerlandesa fija un 30% de alumnas en Ingeniería Aeronáutica y Espacial para combatir los estereotipos de género",
    summary: "La politécnica de Delft busca aumentar la presencia de mujeres en esa especialidad para que en el futuro tengan también más peso en la docencia",
    body: "El Colegio para los Derechos Humanos de Países Bajos, un organismo público independiente, ha dado luz verde a la Universidad Técnica de Delft para que reserve un 30% de las plazas para alumnas en la carrera de Ingeniería Aeronáutica y Espacial a partir del curso 2027-2028. Actualmente, hay cerca de un 22% de mujeres matriculadas en el título de grado (BA, en sus siglas en inglés) y los docentes sostienen que esta infrarrepresentación alimenta los estereotipos de género y obstaculiza a su vez una composición equilibrada del personal docente e investigador.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/educacion/2026-07-08/una-universidad-neerlandesa-fija-un-30-de-alumnas-en-ingenieria-aeronautica-y-espacial-para-combatir-los-estereotipos-de-genero.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 21,
    cat: "geopolitica",
    title: "Coches sin entregar a clientes que pagaron hace siete meses: el limbo tras el cierre de los concesionarios Cobendai",
    summary: "170 trabajadores llevan desde abril sin ingresar sus nóminas y han comenzado a recibir cartas de despido, mientras que casi un centenar de clientes siguen sin poder disponer de sus vehículos",
    body: "Un preconcurso de acreedores y un ERE cuyas negociaciones han concluído sin acuerdo tienen a 170 empleados del Grupo Cobendai sin cobrar sus sueldos desde abril. La compañía, que opera una red de concesionarios y talleres oficiales de Hyundai, Peugeot, Suzuki, Subaru, KGM y MG en la Comunidad de Madrid , atraviesa una grave crisis económica por la que ha comenzado a despedir a sus empleados y que también afecta a los clientes.\n\nCasi 100 compradores aguardan con impaciencia recibir los vehículos que ya han adquirido y que, en algunos casos, llevan esperando desde noviembre de 2025. Una situación que parecía solucionarse cuando Cobendai anunció, a mediados de abril, el inicio de las entregas a las, al menos, 150 personas que denunciaban haber sido estafadas. Sin embargo, el reparto no alcanzó a todos los afectados, quienes temen no llegar a recibir sus coches.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/madrid/2026-07-08/coches-sin-entregar-a-clientes-que-pagaron-hace-siete-meses-el-limbo-tras-el-cierre-de-los-concesionarios-cobendai.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 22,
    cat: "geopolitica",
    title: "Una tarjeta en la obscenidad",
    summary: "El presidente de Estados Unidos sabe que solo la cadena imparable de excesos le garantiza los focos",
    body: "Los mayores escándalos suceden a la vista, sin que haga falta ocultarlos. En realidad, señalar algo y publicarlo ya es la manera más efectiva de taparlo, como en La carta robada de Poe. La sociedad del ruido, que compite por nuestra atención y produce millones de reels y alertas por minuto, no podrá hacer caso a la misma historia por más de cinco minutos, de manera que la obscenidad se ha acabado llevando por delante a la discreción.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-08/una-tarjeta-en-la-obscenidad.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 23,
    cat: "geopolitica",
    title: "La UE cegada, y no por el sol",
    summary: "La ultraderecha está logrando que Europa pierda el liderazgo que en su día tuvo en la transición ecológica",
    body: "Si pasea estos días por París podrá ver el Sena convertido en un aliviadero improvisado de los calores que asolan la ciudad y las ventanas cubiertas con mantas térmicas para intentar detener el calor. Si lo hace por Leipzig, observará que el tranvía ha sido paralizado porque las altas temperaturas han derretido las juntas de las vías por las que circula. Si opta por visitar Londres comprobará que en Inglaterra y Gales se han cerrado escuelas, tiendas y centros comunitarios y se han suspendido trenes por la alerta meteorológica, la más grave de las lanzadas hasta la fecha.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-08/la-ue-cegada-y-no-por-el-sol.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 24,
    cat: "geopolitica",
    title: "Tim Payne, el desconocido defensa neozelandés que se hizo viral y firmó el contrato de su vida",
    summary: "Antes de empezar el Mundial, el ‘youtuber’ argentino Valentín Scarsini animó a seguir en redes a un ignoto defensa neozelandés. Hoy es un fenómeno en internet y acaba de ficharle el club más grande Paraguay",
    body: "Esta es la historia de Tim Payne: un hombre que vive en Wellington, capital de Nueva Zelanda, que no le presta demasiada atención a las redes sociales y que parece contento con un tipo de vida que, por motivos ajenos a su voluntad, de un día para el otro cambiará de manera rotunda. Es defensa del Wellington Phoenix y de la selección de fútbol de Nueva Zelanda y está casado con una fotógrafa costarricense con la que tiene un hijo de dos años.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/eps/2026-07-08/tim-payne-el-desconocido-defensa-neozelandes-que-se-hizo-viral-y-firmo-el-contrato-de-su-vida.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 25,
    cat: "geopolitica",
    title: "Del tardeo lésbico al Lesbian Garros: cómo han cambiado los espacios de encuentro entre mujeres ‘queer’",
    summary: "En el mes del Orgullo LGTBIQ+ de Madrid, Capitán Swing publica ‘Bar Gay. Fragmentos de aquellas fiestas’, un ensayo-memoria que se pregunta qué ocurre cuando desaparecen los espacios que funcionan como archivos de la memoria ‘queer’. En SModa hemos querido trasladar esa pregunta a otro territorio: ¿qué ha sucedido con los espacios lésbicos?",
    body: "Un vistazo a la prensa internacional lo deja claro. Desde 2021, los reportajes sobre la desaparición de bares lésbicos se multiplica. Según datos del Lesbian Bar Project, en Estados Unidos existían unos 200 bares de este tipo a finales de los años ochenta; en 2019 quedaban apenas quince, un descenso de casi el 93%. La escritora Joan Nestle recordaba en Smithsonian Magazine que fue en esos locales donde nacieron los gestos, los códigos y los rituales de una comunidad despreciada que consiguió allí construir su propio mundo.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/smoda/2026-07-08/del-bar-lesbico-al-tardeo-y-al-club-de-lectura-como-han-cambiado-los-espacios-de-encuentro-entre-mujeres-queer.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 26,
    cat: "geopolitica",
    title: "Cristiano se despide del Mundial y abre una nueva era en la selección: “He ganado tres títulos. Antes de mí, Portugal no tenía ninguno”",
    summary: "Roberto Martínez confirma que deja el banquillo de un equipo que se fue del torneo con solo dos triunfos en cinco partidos tras las dudas que generó una propuesta que intentó encajar a toda costa a Ronaldo",
    body: "No hubo ningún otro torneo que frustrara tanto a Cristiano como el Mundial. Desde que en 2006 cayó en la semifinal ante Francia, Ronaldo trató otras cinco veces durante dos décadas de levantar el trofeo. Su último baile, ya con casi 41 años y medio de edad, concluyó el lunes en los octavos de final con la derrota de Portugal contra España (0-1), la misma selección que en 2010, cuando él era uno de los jugadores más diferenciales que existían en el planeta, lo apeó de Sudáfrica en la misma ronda.\n\nEl gol en el 91 de Mikel Merino en Dallas bajó el telón de la carrera del delantero en la Copa del Mundo y comenzó a entreabrir una nueva era en la Seleção tras la influencia inmensa que tuvo en el equipo el deportista más exitoso y global de la historia de Portugal. “Lo di todo, me esforcé al máximo y me voy con la conciencia tranquila. Fue mi último Mundial, sí, pero ahora tendré tiempo para reflexionar y estar con mi familia.\n\nNo voy a tomar decisiones precipitadas en caliente”, dijo Cristiano el lunes, 23 años después de su debut internacional. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-07-08/cristiano-se-despide-del-mundial-y-abre-una-nueva-era-en-la-seleccion-he-ganado-tres-titulos-antes-de-mi-portugal-no-tenia-ninguno.html",
    time: "49 min fa",
    pub_ts: 1783481401,
    tags: [],
  },
  {
    id: 27,
    cat: "conflitti",
    title: "Experts warn Trump is playing politics with US intelligence",
    summary: "Former officials warn that Trump&#039;s intelligence overhaul risks politicising national security.",
    body: "Former officials warn that Trump&#039;s intelligence overhaul risks politicising national security.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/7/8/experts-warn-trump-is-playing-politics-with-us-intelligence?traffic_source=rss",
    time: "35 min fa",
    pub_ts: 1783482268,
    tags: [],
  },
  {
    id: 28,
    cat: "conflitti",
    title: "US strikes Iran despite promised pause for Khamenei funeral",
    summary: "The US launches new strikes on Iran despite a promise by US President Donald Trump to pause attacks.",
    body: "The US launches new strikes on Iran despite a promise by US President Donald Trump to pause attacks.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/7/8/us-strikes-iran-despite-promised-pause-for-khamenei-funeral?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1783473234,
    tags: [],
  },
  {
    id: 29,
    cat: "conflitti",
    title: "How the US-Iran conflict is reshaping Africa’s geopolitical opportunities",
    summary: "The US-Israel war on Iran is forcing African governments to rethink their security and economic priorities.",
    body: "The US-Israel war on Iran is forcing African governments to rethink their security and economic priorities.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/8/how-the-us-iran-conflict-is-reshaping-africas-geopolitical-opportunities?traffic_source=rss",
    time: "3 ore fa",
    pub_ts: 1783472666,
    tags: [],
  },
  {
    id: 30,
    cat: "conflitti",
    title: "Iran war live: US bombs Sirik, Qeshm, Bandar Abbas over Hormuz attacks",
    summary: "Explosions in Iran&#039;s Sirik, Bandar Abbas and Qeshm as US launches attacks after revoking waiver on Iranian oil exports.",
    body: "Explosions in Iran&#039;s Sirik, Bandar Abbas and Qeshm as US launches attacks after revoking waiver on Iranian oil exports.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/liveblog/2026/7/8/iran-war-live-us-bombs-sirik-qeshm-bandar-abbas-over-hormuz-attacks?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1783468800,
    tags: [],
  },
  {
    id: 31,
    cat: "conflitti",
    title: "Russian missiles strike Ukraine’s capital, Kyiv, for third time in a week",
    summary: "The attacks have triggered fires in two districts of Kyiv, according to the city&#039;s mayor.",
    body: "The attacks have triggered fires in two districts of Kyiv, according to the city&#039;s mayor.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/7/russian-missile-strikes-hit-ukraines-capital-kyiv-for-third-time-in-a-week?traffic_source=rss",
    time: "5 ore fa",
    pub_ts: 1783464815,
    tags: [],
  },
  {
    id: 32,
    cat: "conflitti",
    title: "Egypt buoyed by praise for World Cup heroics despite controversial exit",
    summary: "From fans in Gaza to world leaders and supporters on social media, Egypt won hearts, even if they lost to Argentina.",
    body: "From fans in Gaza to world leaders and supporters on social media, Egypt won hearts, even if they lost to Argentina.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/sports/2026/7/7/egypt-buoyed-by-praise-for-world-cup-heroics-despite-controversial-exit?traffic_source=rss",
    time: "5 ore fa",
    pub_ts: 1783464370,
    tags: [],
  },
  {
    id: 33,
    cat: "conflitti",
    title: "US launches strikes on southern Iran, Tehran vows ‘crushing response’",
    summary: "US strikes in Iran come a day after Qatari, Saudi tankers hit in attacks in Strait of Hormuz.",
    body: "US strikes in Iran come a day after Qatari, Saudi tankers hit in attacks in Strait of Hormuz.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/7/us-says-strikes-launched-as-explosions-heard-in-southern-iran?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1783459276,
    tags: [],
  },
  {
    id: 34,
    cat: "conflitti",
    title: "Prolonged hospitalisation of US Republican Mitch McConnell raises questions",
    summary: "The senator has been hospitalised since June 14 with few details released, raising questions over his return to work.",
    body: "The senator has been hospitalised since June 14 with few details released, raising questions over his return to work.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/7/prolonged-hospitalisation-of-us-republican-mitch-mcconnell-raises-questions?traffic_source=rss",
    time: "7 ore fa",
    pub_ts: 1783455976,
    tags: [],
  },
  {
    id: 35,
    cat: "conflitti",
    title: "Canadian province sues OpenAI over alleged ChatGPT-linked shooting warnings",
    summary: "Lawsuit claims OpenAI ignored calls to alert authorities about violent ChatGPT prompts tied to mass shooting suspect.",
    body: "Lawsuit claims OpenAI ignored calls to alert authorities about violent ChatGPT prompts tied to mass shooting suspect.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/7/canadian-province-sues-openai-over-alleged-chatgpt-linked-shooting-warnings?traffic_source=rss",
    time: "8 ore fa",
    pub_ts: 1783455293,
    tags: [],
  },
  {
    id: 36,
    cat: "conflitti",
    title: "Trump lashes out at NATO as first day of summit wraps in Turkiye",
    summary: "Leaders have gathered in Ankara for a two-day summit slated to cover defence spending and the Russia-Ukraine war.",
    body: "Leaders have gathered in Ankara for a two-day summit slated to cover defence spending and the Russia-Ukraine war.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/7/trump-lashes-out-at-nato-as-first-day-of-summit-wraps-in-turkiye?traffic_source=rss",
    time: "8 ore fa",
    pub_ts: 1783454920,
    tags: [],
  },
  {
    id: 37,
    cat: "conflitti",
    title: "Trump criticises NATO allies over Iran conflict support",
    summary: "US President Donald Trump criticised NATO allies for refusing to back the United States during its conflict with Iran.",
    body: "US President Donald Trump criticised NATO allies for refusing to back the United States during its conflict with Iran.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/7/7/trump-criticises-nato-allies-over-iran-conflict-support?traffic_source=rss",
    time: "9 ore fa",
    pub_ts: 1783451765,
    tags: [],
  },
  {
    id: 38,
    cat: "conflitti",
    title: "‘They brought me here to kill me’ says Gaza doctor in Israeli prison",
    summary: "‘They brought me here to kill me’ says Gaza doctor in Israeli prison",
    body: "‘They brought me here to kill me’ says Gaza doctor in Israeli prison",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/7/7/they-brought-me-here-to-kill-me-says-gaza-doctor-in-israeli-prison?traffic_source=rss",
    time: "9 ore fa",
    pub_ts: 1783449895,
    tags: [],
  },
  {
    id: 39,
    cat: "ai",
    title: "Meta’s glasses will turn off the camera if you tamper with the privacy light",
    summary: "Amid public backlash over its smart glasses, Meta announced that it will be updating its glasses with a new feature that will disable the camera when it detects that someone has tampered with or destroyed the glasses' privacy LED light. The update is meant to address modders who have taken actions such as physically drilling [&#8230;]",
    body: "Even so, the privacy LED light is still hard to see. It’s on in this photo. | Photo by Amelia Holowaty Krales / The Verge Amid public backlash over its smart glasses, Meta announced that it will be updating its glasses with a new feature that will disable the camera when it detects that someone has tampered with or destroyed the glasses' privacy LED light. The update is meant to address modders who have taken actions such as physically drilling into the LED light .\n\nMeta has previously tried to discourage tampering with the LED light. For example, starting with its second generation glasses, blocking the light with tape or other objects will trigger a prompt asking users to uncover the recording light. However, many modders have found various workarounds for tha …",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/962514/meta-privacy-light-tampering-smart-glasses-update",
    time: "4 ore fa",
    pub_ts: 1783468519,
    tags: [],
  },
  {
    id: 40,
    cat: "ai",
    title: "Final extension: Startup Battlefield Australia applications now close July 20",
    summary: "If you're building something ambitious, this is a fast track to the people who can move your startup forward.",
    body: "If you're building something ambitious, this is a fast track to the people who can move your startup forward.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/final-extension-startup-battlefield-australia-applications-now-close-july-20/",
    time: "5 ore fa",
    pub_ts: 1783463400,
    tags: [],
  },
  {
    id: 41,
    cat: "ai",
    title: "Meta just launched a new AI generator, Muse Image, and users are already pushing back over use of their photos",
    summary: "The new image-generating model has numerous use cases, including advertising and decorating, and creator-based opportunities.",
    body: "The new image-generating model has numerous use cases, including advertising and decorating, and creator-based opportunities.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/meta-rolls-out-muse-a-new-ai-image-generator/",
    time: "6 ore fa",
    pub_ts: 1783462690,
    tags: [],
  },
  {
    id: 42,
    cat: "ai",
    title: "Of course viewers are giving up on Netflix shows",
    summary: "Even though Netflix is the world's most popular paid streaming service, the company has been struggling to keep viewers watching its series after their first seasons. Beef - the streamer's anthology about people locked in feuds - lost 70 percent of its viewership when it returned earlier this year. There seems to be some confusion [&#8230;]",
    body: "Even though Netflix is the world's most popular paid streaming service, the company has been struggling to keep viewers watching its series after their first seasons. Beef - the streamer's anthology about people locked in feuds - lost 70 percent of its viewership when it returned earlier this year. There seems to be some confusion as to why people aren't champing at the bit to dive back into once-popular projects like the live-action adaptations of Avatar: The Last Airbender and One Piece .\n\nNetflix is reportedly hard at work trying to figure out what, exactly, is prompting subscribers to jump ship in droves. But if you've spent any time payin …",
    source: "The Verge",
    url: "https://www.theverge.com/entertainment/962382/netflix-season-two-viewrship-dropoff-beef-avatar-one-piece-tiktok",
    time: "6 ore fa",
    pub_ts: 1783461519,
    tags: [],
  },
  {
    id: 43,
    cat: "ai",
    title: "Netflix is about to host videos from BuzzFeed, Condé Nast, and other publishers",
    summary: "Starting on August 3rd, Netflix's streaming library will include video content from dozens of digital media brands including BuzzFeed, Cond&#233; Nast, Hearst Magazines, People Inc, and Tastemade. As reported earlier by TechCrunch, the deal includes a mix of licensed past videos and new ongoing series that would have typically been published on YouTube or other [&#8230;]",
    body: "Starting on August 3rd, Netflix's streaming library will include video content from dozens of digital media brands including BuzzFeed, Cond&eacute; Nast, Hearst Magazines, People Inc, and Tastemade. As reported earlier by TechCrunch , the deal includes a mix of licensed past videos and new ongoing series that would have typically been published on YouTube or other online platforms, like Architectural Digest 's \"Open Door\" or Vanity Fair 's \"Lie Detector Test.\" As Netflix puts it, the deal will allow subscribers to watch content \"from around the Internet without having to leave Netflix.\" The announcement follows a Bloomberg report earlier this week …",
    source: "The Verge",
    url: "https://www.theverge.com/streaming/962528/netflix-digital-media-brands-streaming",
    time: "6 ore fa",
    pub_ts: 1783460239,
    tags: [],
  },
  {
    id: 44,
    cat: "ai",
    title: "Meta’s new Muse Image model can pull other Instagram users into AI photos",
    summary: "Meta is launching the first AI image generation model made by its Superintelligence Labs division. The Muse Image model now powers the image-making tools across the Meta AI app, Instagram, and WhatsApp, and it's coming soon to Facebook and Messenger, according to an announcement on Tuesday. It's part of the growing Muse family of AI [&#8230;]",
    body: "Meta is launching the first AI image generation model made by its Superintelligence Labs division. The Muse Image model now powers the image-making tools across the Meta AI app, Instagram, and WhatsApp, and it's coming soon to Facebook and Messenger, according to an announcement on Tuesday . It's part of the growing Muse family of AI models that replace Meta's Llama lineup. Alexandr Wang, who Meta hired to head up its Superintelligence Labs last year, says on Threads that Muse Image is \"agentic,\" meaning it works with its Muse Spark large language model \"to reason through your prompt, search the web, and plan before it generates.\" Meta is al …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/962485/meta-muse-image-ai-model-instagram",
    time: "7 ore fa",
    pub_ts: 1783456318,
    tags: [],
  },
  {
    id: 45,
    cat: "ai",
    title: "Why the rise of open source AI isn’t hurting Anthropic … yet",
    summary: "Open source models’ success isn’t coming at the expense of frontier labs. Instead, they each seem to capture two phases of the same life cycle.",
    body: "Open source models’ success isn’t coming at the expense of frontier labs. Instead, they each seem to capture two phases of the same life cycle.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/why-the-rise-of-open-source-ai-isnt-hurting-anthropic-yet/",
    time: "8 ore fa",
    pub_ts: 1783454672,
    tags: [],
  },
  {
    id: 46,
    cat: "ai",
    title: "Microsoft joins AI cost-cutting trend by relying more on its own models",
    summary: "Microsoft is the latest Silicon Valley giant to cut back on its AI spending.",
    body: "Microsoft is the latest Silicon Valley giant to cut back on its AI spending.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/microsoft-joins-ai-cost-cutting-trend-by-relying-more-on-its-own-models/",
    time: "8 ore fa",
    pub_ts: 1783454300,
    tags: [],
  },
  {
    id: 47,
    cat: "ai",
    title: "Discord admits AI moderation bug wrongfully banned users over harmless images",
    summary: "The company confirmed that the issue had been affecting accounts since May, with an additional 200 users banned over the weekend before its team identified and fixed the problem.",
    body: "The company confirmed that the issue had been affecting accounts since May, with an additional 200 users banned over the weekend before its team identified and fixed the problem.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/discord-admits-ai-moderation-bug-wrongfully-banned-users-over-harmless-images/",
    time: "8 ore fa",
    pub_ts: 1783452518,
    tags: [],
  },
  {
    id: 48,
    cat: "ai",
    title: "Google’s Pixel event is set for August 12",
    summary: "Google's upcoming event in August will introduce new Pixel devices.",
    body: "Google's upcoming event in August will introduce new Pixel devices.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/googles-pixel-event-is-set-for-august-12/",
    time: "9 ore fa",
    pub_ts: 1783449509,
    tags: [],
  },
  {
    id: 49,
    cat: "ai",
    title: "Figma acquires team behind a vibe-coding app",
    summary: "The Y Combinator-backed company started a vibe-coding platform and later built an agent-creation product.",
    body: "The Y Combinator-backed company started a vibe-coding platform and later built an agent-creation product.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/figma-acquires-team-behind-a-vibe-coding-app/",
    time: "9 ore fa",
    pub_ts: 1783449421,
    tags: [],
  },
  {
    id: 50,
    cat: "ai",
    title: "X says top accounts steal videos from other users as it announces new video tools",
    summary: "Nikita Bier, X's head of product, said in a post on Monday that \"[m]any videos from top accounts are simply stolen from other users, sometimes 5 years after they originally went viral,\" while noting that videos on the platform \"make up close to half the impressions on X.\" According to Bier, X is launching a [&#8230;]",
    body: "Nikita Bier, X's head of product, said in a post on Monday that \"[m]any videos from top accounts are simply stolen from other users, sometimes 5 years after they originally went viral,\" while noting that videos on the platform \"make up close to half the impressions on X.\" According to Bier, X is launching a new in-app video editor and recorder to address this \"recycled content,\" so that \"some videos on X can finally be original content that doesn't exist on other platforms.\" As previously reported by TechCrunch , the new video tools are available now on X's iOS app, and include an option for overlaying captions in multiple languages and a \"g …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/962415/x-video-editor-recycled-content",
    time: "9 ore fa",
    pub_ts: 1783448888,
    tags: [],
  },
  {
    id: 51,
    cat: "ai",
    title: "The ‘G-Wagen of golf carts’ could be the ideal second car",
    summary: "While the auto industry wrings its hands over the electric vehicle market, sweating details like aerodynamic efficiency and range anxiety, a new EV startup based in Lisbon, Portugal, is zagging in a different direction. Amble's new electric buggy won't impress anyone with its 0-60 time or its self-driving features (it has none). Instead, it takes [&#8230;]",
    body: "While the auto industry wrings its hands over the electric vehicle market, sweating details like aerodynamic efficiency and range anxiety, a new EV startup based in Lisbon, Portugal, is zagging in a different direction. Amble's new electric buggy won't impress anyone with its 0-60 time or its self-driving features (it has none). Instead, it takes a stab at the belief that cars have gotten too big, too fast, and perhaps could use a bit of a downgrade in both departments.\n\nThe Amble One is a premium, street-legal buggy with a gorgeous neo-retro design that's currently being marketed to locations where traditional cars are unnecessary or too la …",
    source: "The Verge",
    url: "https://www.theverge.com/transportation/962187/amble-golf-cart-moon-buggy-ev-design-price-specs",
    time: "10 ore fa",
    pub_ts: 1783446771,
    tags: [],
  },
  {
    id: 52,
    cat: "ai",
    title: "ABC tells the government to get out of its newsrooms",
    summary: "ABC is firing back at the Federal Communications Commission after the agency opened an investigation into The View's airtime of political candidates. In a letter to the FCC on Tuesday, ABC argues that the agency's actions pose a risk to editorial independence by targeting programs \"perceived as unfriendly to the current administration,\" as reported earlier [&#8230;]",
    body: "ABC is firing back at the Federal Communications Commission after the agency opened an investigation into The View 's airtime of political candidates. In a letter to the FCC on Tuesday, ABC argues that the agency's actions pose a risk to editorial independence by targeting programs \"perceived as unfriendly to the current administration,\" as reported earlier by The Wrap . In February, the FCC Chair Brendan Carr confirmed that he's reexamining The View 's classification as a \"bona fide\" news program after the talk show held an interview with Rep.\n\nJames Talarico (D-TX), who is running for a spot in the Senate. The View 's classification exempts it …",
    source: "The Verge",
    url: "https://www.theverge.com/policy/962342/abc-fcc-the-view-free-speech",
    time: "10 ore fa",
    pub_ts: 1783446458,
    tags: [],
  },
  {
    id: 53,
    cat: "ai",
    title: "Anthropic is launching Claude Cowork on mobile and web",
    summary: "Starting Tuesday, Anthropic's Claude Cowork AI platform will be available on mobile and web for the first time. The expanded access is rolling out first to Max subscribers and coming to Claude users on other plans \"in the coming weeks.\" Claude Cowork was previously only accessible through the Claude desktop app for macOS and Windows, [&#8230;]",
    body: "Starting Tuesday, Anthropic's Claude Cowork AI platform will be available on mobile and web for the first time. The expanded access is rolling out first to Max subscribers and coming to Claude users on other plans \"in the coming weeks.\" Claude Cowork was previously only accessible through the Claude desktop app for macOS and Windows, but now users on iOS and Android can also use it. However, Anthropic says the \"full experience\" for Cowork will still be on the desktop app, including features like local file access.\n\nCowork sessions will also now run in the cloud by default, so you can continue them across different devices or run Cowork ta …",
    source: "The Verge",
    url: "https://www.theverge.com/ai-artificial-intelligence/961978/anthropic-claude-cowork-mobile-web",
    time: "10 ore fa",
    pub_ts: 1783446419,
    tags: [],
  },
  {
    id: 54,
    cat: "ai",
    title: "Netflix dabbles in shorter video content with its new set of publisher deals with Variety, others",
    summary: "Netflix is bringing 2- to 20-minute videos to its platform through new partnerships with digital publishers, including Rolling Stone and Variety.",
    body: "Netflix is bringing 2- to 20-minute videos to its platform through new partnerships with digital publishers, including Rolling Stone and Variety.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/netflix-dabbles-in-shorter-video-content-with-its-new-set-of-publisher-deals-with-variety-others/",
    time: "10 ore fa",
    pub_ts: 1783445075,
    tags: [],
  },
  {
    id: 55,
    cat: "ai",
    title: "Google announces Pixel 11 launch event in August",
    summary: "Google is hosting its next Made by Google launch event for Pixel hardware on August 12th in New York City, according to an invitation sent by Google to The Verge. Unusually, the event is taking place in the evening: It'll kick off at 6PM ET that day. The email also includes a brief animation teasing [&#8230;]",
    body: "Google is hosting its next Made by Google launch event for Pixel hardware on August 12th in New York City, according to an invitation sent by Google to The Verge . Unusually, the event is taking place in the evening: It'll kick off at 6PM ET that day. The email also includes a brief animation teasing what appears to be a phone in the Pixel 11 family that's gold. Pixel 11 leaks that have popped up so far show that the base phone could have slimmer bezels than the Pixel 10 and a solid black camera bar.\n\nLeaks of Pixel 11 Pro indicate the phone could be a touch thinner than the Pixel 10 Pro . And the Pixel 11 Pro Fold could also be thinner than …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/962313/made-by-google-pixel-11-launch-event",
    time: "10 ore fa",
    pub_ts: 1783444968,
    tags: [],
  },
  {
    id: 56,
    cat: "ai",
    title: "Hacked, leaked, and held for ransom: The worst breaches of 2026 so far",
    summary: "From a massive DOGE data breach and the hacking of critical energy and water systems to the hack of an FBI surveillance system, here are the most damaging security incidents and data breaches of 2026.",
    body: "From a massive DOGE data breach and the hacking of critical energy and water systems to the hack of an FBI surveillance system, here are the most damaging security incidents and data breaches of 2026.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/the-worst-hacks-and-breaches-of-2026-so-far/",
    time: "11 ore fa",
    pub_ts: 1783442700,
    tags: [],
  },
  {
    id: 57,
    cat: "ai",
    title: "Claude Cowork expands to mobile and web",
    summary: "With this update, users can start a task from their desk, get status updates on their phone, and pick up the finished output later — even if their laptop is closed.",
    body: "With this update, users can start a task from their desk, get status updates on their phone, and pick up the finished output later — even if their laptop is closed.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/07/the-coding-agent-wars-are-spilling-into-the-rest-of-the-office-claude-cowork/",
    time: "11 ore fa",
    pub_ts: 1783441638,
    tags: [],
  },
  {
    id: 58,
    cat: "ai",
    title: "Doom developer id reportedly cut in half as part of Xbox layoffs",
    summary: "As part of the mass layoffs hitting Xbox, Doom developer id Software has laid off around 50 percent of its staff, according to Game Developer. One source claimed to the publication that the cuts equate to more than 90 redundancies. Another source said that id's QA department was significantly impacted. The report was published the [&#8230;]",
    body: "As part of the mass layoffs hitting Xbox, Doom developer id Software has laid off around 50 percent of its staff, according to Game Developer . One source claimed to the publication that the cuts equate to more than 90 redundancies. Another source said that id's QA department was significantly impacted. The report was published the same day that id is releasing a major expansion for its latest Doom game .\n\nA former id employee affected by the cuts, Michael Maynard, corroborated the figure in a LinkedIn post , saying that the layoffs affected \"roughly\" 50 percent of the company. \"We created arguably THE BEST first person engine technology in the …",
    source: "The Verge",
    url: "https://www.theverge.com/games/962223/doom-id-software-xbox-layoffs",
    time: "12 ore fa",
    pub_ts: 1783440588,
    tags: [],
  },
  {
    id: 59,
    cat: "economia-tech",
    title: "US launches new wave of Iran strikes after attacks on tankers",
    summary: "Trump administration also revokes licence allowing Islamic republic’s oil sales, sending crude prices higher",
    body: "Trump administration also revokes licence allowing Islamic republic’s oil sales, sending crude prices higher",
    source: "Financial Times",
    url: "https://www.ft.com/content/c7dac217-4a77-4640-9aa4-17ae7b0d5c0c",
    time: "10 min fa",
    pub_ts: 1783483763,
    tags: [],
  },
  {
    id: 60,
    cat: "economia-tech",
    title: "Ibm punta sul quantum per conquistare le medie imprese",
    summary: "Nel 2023 era stata raggiunta la capacità del quantum computing di uguagliare la capacità dei computer tradizionali, quest’anno Ibm dovrebbe raggiungere il “quantum advantage”, con performance e qualità decisamente superiori,...",
    body: "Nel 2023 era stata raggiunta la capacità del quantum computing di uguagliare la capacità dei computer tradizionali, quest’anno Ibm dovrebbe raggiungere il “quantum advantage”, con performance e qualità decisamente superiori,...",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/ibm-punta-quantum-conquistare-medie-imprese-AJ00J1B",
    time: "13 min fa",
    pub_ts: 1783483578,
    tags: [],
  },
  {
    id: 61,
    cat: "economia-tech",
    title: "The battle for the future of democratic republics",
    summary: "Celebrations in the US for its 250th anniversary are in part a wake",
    body: "Celebrations in the US for its 250th anniversary are in part a wake",
    source: "Financial Times",
    url: "https://www.ft.com/content/2dcabc77-4502-4eef-848f-b45db14ccd87",
    time: "19 min fa",
    pub_ts: 1783483228,
    tags: [],
  },
  {
    id: 62,
    cat: "economia-tech",
    title: "Meta tests ‘super sensing’ AI glasses that can record every moment",
    summary: "Mark Zuckerberg’s hardware ambitions are edging into a new privacy fight over who gets recorded",
    body: "Mark Zuckerberg’s hardware ambitions are edging into a new privacy fight over who gets recorded",
    source: "Financial Times",
    url: "https://www.ft.com/content/ac282450-91a8-4597-8f60-9e6ef416865a",
    time: "19 min fa",
    pub_ts: 1783483221,
    tags: [],
  },
  {
    id: 63,
    cat: "economia-tech",
    title: "Santander axes top China banker and scraps perks in Asia overhaul",
    summary: "Spanish lender shifting focus of regional corporate and investment banking operations to south-east Asia",
    body: "Spanish lender shifting focus of regional corporate and investment banking operations to south-east Asia",
    source: "Financial Times",
    url: "https://www.ft.com/content/2169b73c-7583-4d28-91d5-6459846ad769",
    time: "19 min fa",
    pub_ts: 1783483219,
    tags: [],
  },
  {
    id: 64,
    cat: "economia-tech",
    title: "Streamers ignore omnivorous consumers at their peril",
    summary: "Sony’s plan to drop physical discs endangers the company and its customers",
    body: "Sony’s plan to drop physical discs endangers the company and its customers",
    source: "Financial Times",
    url: "https://www.ft.com/content/13ae8962-954d-4b83-bc90-29ca32c5e578",
    time: "19 min fa",
    pub_ts: 1783483219,
    tags: [],
  },
  {
    id: 65,
    cat: "economia-tech",
    title: "Palantir: too tied to Trump?",
    summary: "Pushback to the tech group’s politics may threaten the core of its $330bn business",
    body: "Pushback to the tech group’s politics may threaten the core of its $330bn business",
    source: "Financial Times",
    url: "https://www.ft.com/content/21038b20-646e-4773-a473-110c2d62ab15",
    time: "19 min fa",
    pub_ts: 1783483209,
    tags: [],
  },
  {
    id: 66,
    cat: "economia-tech",
    title: "Economia del mare, valore a 225 miliardi e crescono le imprese",
    summary: "Cresce la blue economy italiana, che arriva oggi a quasi 225 miliardi di valore, pari all’11,4% del Pil nazionale, con il Mezzogiorno che si conferma l’area col maggior peso nel...",
    body: "Cresce la blue economy italiana, che arriva oggi a quasi 225 miliardi di valore, pari all’11,4% del Pil nazionale, con il Mezzogiorno che si conferma l’area col maggior peso nel...",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/economia-mare-valore-225-miliardi-e-crescono-imprese-AJYWIoB",
    time: "19 min fa",
    pub_ts: 1783483200,
    tags: [],
  },
  {
    id: 67,
    cat: "economia-tech",
    title: "I magazzini diventano fonte di liquidità Prima operazione di Cdp e Cherry Bank",
    summary: "Dieci milioni per l’azienda vicentina dell’alimentare Brazzale. Iniziativa apripista, modello per altri settori e player",
    body: "Dieci milioni per l’azienda vicentina dell’alimentare Brazzale. Iniziativa apripista, modello per altri settori e player",
    source: "Il Sole 24 Ore",
    url: "https://www.ilsole24ore.com/art/i-magazzini-diventano-fonte-liquidita-prima-operazione-cdp-e-cherry-bank-AJg3VhB",
    time: "1 ora fa",
    pub_ts: 1783480117,
    tags: [],
  },
  {
    id: 68,
    cat: "economia-tech",
    title: "Tencent WeChat AI Agent Shows Promise in Super-App Fight: Review",
    summary: "Tencent Holdings Ltd. is fighting to restore its reputation as a tech innovator after falling behind in the race to develop groundbreaking frontier AI models. It’s taking an important step in that direction with Xiaowei: a prototype AI agent that it envisions eventually running errands for a billion-plus users across a WeChat ecosystem spanning millions of apps.",
    body: "Tencent Holdings Ltd. is fighting to restore its reputation as a tech innovator after falling behind in the race to develop groundbreaking frontier AI models. It’s taking an important step in that direction with Xiaowei: a prototype AI agent that it envisions eventually running errands for a billion-plus users across a WeChat ecosystem spanning millions of apps.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-08/tencent-wechat-ai-agent-shows-promise-in-super-app-fight-review",
    time: "1 ora fa",
    pub_ts: 1783479622,
    tags: [],
  },
  {
    id: 69,
    cat: "economia-tech",
    title: "KKR-Backed SmartHR Is Said to Delay Tokyo IPO Beyond This Year",
    summary: "Japanese human resources platform operator SmartHR Inc. has delayed its plans for an initial public offering to next year at the earliest as investors viewed the company’s targeted valuation as too high, according to people familiar with the matter.",
    body: "Japanese human resources platform operator SmartHR Inc. has delayed its plans for an initial public offering to next year at the earliest as investors viewed the company’s targeted valuation as too high, according to people familiar with the matter.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-08/kkr-backed-smarthr-is-said-to-delay-tokyo-ipo-beyond-this-year",
    time: "1 ora fa",
    pub_ts: 1783479369,
    tags: [],
  },
  {
    id: 70,
    cat: "economia-tech",
    title: "Samsung Scales Up Storage Production for Nvidia’s Vera Rubin",
    summary: "Samsung Electronics Co. has begun mass production of its most advanced data center storage drive, which is set for use inside Nvidia Corp.’s upcoming Vera Rubin platform.",
    body: "Samsung Electronics Co. has begun mass production of its most advanced data center storage drive, which is set for use inside Nvidia Corp.’s upcoming Vera Rubin platform.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-07/samsung-mass-produces-storage-drives-for-nvidia-s-vera-rubin",
    time: "5 ore fa",
    pub_ts: 1783465800,
    tags: [],
  },
  {
    id: 71,
    cat: "economia-tech",
    title: "Samsung to Get Jump on Apple’s First Foldable With New Phones in July",
    summary: "Samsung Electronics Co. will host its next Galaxy Unpacked event on July 22, when the leading foldable phone maker is expected to unveil a Galaxy Z Fold 8 with a shorter and wider design that resembles Apple Inc.’s planned folding iPhone.",
    body: "A Samsung Galaxy Z Flip 7 and Galaxy Z Fold 7 during Galaxy Unpacked at the Brooklyn Navy Yard in New York, US, on Wednesday, July 9, 2025. Samsung Electronics Co. unveiled two upgraded smartwatches and new artificial intelligence software in its latest attempt to stand out in a crowded market led by Apple.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-07/samsung-to-get-jump-on-apple-s-first-foldable-launch-with-galaxy-fold-8-july-22",
    time: "5 ore fa",
    pub_ts: 1783465220,
    tags: [],
  },
  {
    id: 72,
    cat: "economia-tech",
    title: "Billionaires Arrive for the Annual Sun Valley Conference",
    summary: "Billionaires descend today on Sun Valley, Idaho, for the Allen & Co. annual gathering of media, technology and finance moguls. Some of the attendees include Hank Paulson, David Zaslav, Neal Mohan and Barry Diller. (Source: Bloomberg)",
    body: "Billionaires descend today on Sun Valley, Idaho, for the Allen & Co. annual gathering of media, technology and finance moguls. Some of the attendees include Hank Paulson, David Zaslav, Neal Mohan and Barry Diller. (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-07/billionaires-arrive-for-the-annual-sun-valley-conference-video",
    time: "5 ore fa",
    pub_ts: 1783463174,
    tags: [],
  },
  {
    id: 73,
    cat: "economia-tech",
    title: "Chip Stocks Tumble on AI Anxiety | The Close 7/7/2026",
    summary: "Bloomberg Television brings you the latest news and analysis leading up to the final minutes and seconds before and after the closing bell on Wall Street. Today's guests are Cboe Global Markets VP, Head of Derivatives Market Intelligence Mandy Xu, TeraWulf Chairman & CEO Paul Prager, CFRA Research Equity Research Analyst Keith Snyder, Former NATO Ambassador Kay Bailey Hutchison, JPMorgan Asset…",
    body: "Bloomberg Television brings you the latest news and analysis leading up to the final minutes and seconds before and after the closing bell on Wall Street. Today's guests are Cboe Global Markets VP, Head of Derivatives Market Intelligence Mandy Xu, TeraWulf Chairman & CEO Paul Prager, CFRA Research Equity Research Analyst Keith Snyder, Former NATO Ambassador Kay Bailey Hutchison, JPMorgan Asset Management Global Market Strategist Jordan Jackson, Bernstein Research US Semiconductors Senior Analyst Stacy Rasgon, American Century Investments CEO Jonathan Thomas, Neuberger Private Markets Global Head Tony Tutrone, & Spring Health CEO & Co-Founder April Koh.\n\n(Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-07/the-close-7-7-2026-video",
    time: "6 ore fa",
    pub_ts: 1783462408,
    tags: [],
  },
  {
    id: 74,
    cat: "economia-tech",
    title: "Le Pen is posing as the victim of a politicised judiciary",
    summary: "The strategy might play well with the far-right leader’s core voters, but the French as a whole don’t buy it",
    body: "The strategy might play well with the far-right leader’s core voters, but the French as a whole don’t buy it",
    source: "Financial Times",
    url: "https://www.ft.com/content/82523acf-a51d-4e6a-bb19-60d0c7899b6d",
    time: "6 ore fa",
    pub_ts: 1783460234,
    tags: [],
  },
  {
    id: 75,
    cat: "economia-tech",
    title: "French far-right leader Le Pen says she will run for president",
    summary: "Politician sets up unprecedented election campaign next year after judges uphold her conviction for embezzlement",
    body: "Politician sets up unprecedented election campaign next year after judges uphold her conviction for embezzlement",
    source: "Financial Times",
    url: "https://www.ft.com/content/3c0ecc58-630b-4d74-8abd-b17eb73116cf",
    time: "6 ore fa",
    pub_ts: 1783460047,
    tags: [],
  },
  {
    id: 76,
    cat: "economia-tech",
    title: "TeraWulf CEO Excited About Anthropic Data Center Agreement",
    summary: "TeraWulf CEO Paul Prager says a new 20-year lease agreement with Anthropic is a major vote of confidence in the company’s AI infrastructure strategy. Speaking on \"Bloomberg The Close,\" Prager also discusses plans for a purpose-built AI campus at TeraWulf’s Kentucky site and what the long-term partnership means for future growth. (Source: Bloomberg)",
    body: "TeraWulf CEO Paul Prager says a new 20-year lease agreement with Anthropic is a major vote of confidence in the company’s AI infrastructure strategy. Speaking on \"Bloomberg The Close,\" Prager also discusses plans for a purpose-built AI campus at TeraWulf’s Kentucky site and what the long-term partnership means for future growth. (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-07/terawulf-ceo-on-anthropic-data-center-agreement-video",
    time: "7 ore fa",
    pub_ts: 1783458469,
    tags: [],
  },
  {
    id: 77,
    cat: "economia-tech",
    title: "Democrats Aren't Obstacle For Clarity Act: Cuomo",
    summary: "Andrew Cuomo, former New York governor, joins Katie Greifeld and Isabelle Lee on \"Bloomberg Crypto.\" (Source: Bloomberg)",
    body: "Andrew Cuomo, former New York governor, joins Katie Greifeld and Isabelle Lee on \"Bloomberg Crypto.\" (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-07/democrats-aren-t-obstacle-for-clarity-act-cuomo-video",
    time: "7 ore fa",
    pub_ts: 1783458095,
    tags: [],
  },
  {
    id: 78,
    cat: "economia-tech",
    title: "Andrew Cuomo Discuses Trump Crypto Earnings",
    summary: "Andrew Cuomo, former New York governor, joins Katie Greifeld and Isabelle Lee on \"Bloomberg Crypto.\" President Trump reported earning at least $1.4 billion in 2025 from crypto and memecoin-related businesses, according to his latest annual financial disclosure. (Source: Bloomberg)",
    body: "Andrew Cuomo, former New York governor, joins Katie Greifeld and Isabelle Lee on \"Bloomberg Crypto.\" President Trump reported earning at least $1.4 billion in 2025 from crypto and memecoin-related businesses, according to his latest annual financial disclosure. (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-07/andrew-cuomo-discuses-trump-crypto-earnings-video",
    time: "7 ore fa",
    pub_ts: 1783457602,
    tags: [],
  },
];
