// Generato automaticamente il 2026-07-06 04:11 UTC da scripts/fetch_news.py
// NON modificare manualmente: viene sovrascritto ogni ora dalla GitHub Action.
var NEWS_TIMESTAMP = 1783311055;

const RSS_SOURCES = [
  {
    "name": "ANSA",
    "url": "https://www.ansa.it/sito/ansait_rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Corriere",
    "url": "https://xml2.corrieredellasera.it/rss/homepage.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Il Post",
    "url": "https://www.ilpost.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Sky TG24",
    "url": "https://tg24.sky.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "AGI",
    "url": "https://www.agi.it/feed/rss.xml",
    "cat": "politica-italiana"
  },
  {
    "name": "Pagella Politica",
    "url": "https://pagellapolitica.it/feed",
    "cat": "politica-italiana"
  },
  {
    "name": "Facta",
    "url": "https://facta.news/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Valigia Blu",
    "url": "https://www.valigiablu.it/feed/",
    "cat": "politica-italiana"
  },
  {
    "name": "Limes",
    "url": "https://www.limesonline.com/feed",
    "cat": "geopolitica"
  },
  {
    "name": "Internazionale",
    "url": "https://www.internazionale.it/feed/tutto",
    "cat": "geopolitica"
  },
  {
    "name": "BBC World",
    "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "AP",
    "url": "https://apnews.com/hub/world-news?output=rss",
    "cat": "geopolitica"
  },
  {
    "name": "The Economist",
    "url": "https://www.economist.com/international/rss.xml",
    "cat": "geopolitica"
  },
  {
    "name": "El Pais",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "cat": "geopolitica"
  },
  {
    "name": "Reuters",
    "url": "https://feeds.reuters.com/reuters/worldNews",
    "cat": "conflitti"
  },
  {
    "name": "Al Jazeera",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "cat": "conflitti"
  },
  {
    "name": "AP conflitti",
    "url": "https://apnews.com/hub/wars-and-conflicts?output=rss",
    "cat": "conflitti"
  },
  {
    "name": "The Verge",
    "url": "https://www.theverge.com/rss/index.xml",
    "cat": "ai"
  },
  {
    "name": "Wired IT",
    "url": "https://www.wired.it/feed/rss",
    "cat": "ai"
  },
  {
    "name": "TechCrunch",
    "url": "https://techcrunch.com/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Post Tech",
    "url": "https://www.ilpost.it/tecnologia/feed/",
    "cat": "ai"
  },
  {
    "name": "Il Sole 24 Ore",
    "url": "https://www.ilsole24ore.com/rss/economia.xml",
    "cat": "economia-tech"
  },
  {
    "name": "Bloomberg Tech",
    "url": "https://feeds.bloomberg.com/technology/news.rss",
    "cat": "economia-tech"
  },
  {
    "name": "Financial Times",
    "url": "https://www.ft.com/rss/home",
    "cat": "economia-tech"
  },
  {
    "name": "The Economist Ec",
    "url": "https://www.economist.com/business/rss.xml",
    "cat": "economia-tech"
  }
];

const NEWS = [
  {
    id: 1,
    cat: "politica-italiana",
    title: "'Sessiste le parole della pm', Strasburgo condanna l'Italia",
    summary: "'Normale che l'uomo superi un po' di resistenza della donna'. La donna che ha denunciato: 'Rinasco'",
    body: "'Normale che l'uomo superi un po' di resistenza della donna'. La donna che ha denunciato: 'Rinasco'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/2026/07/05/sessiste-le-parole-della-pm-strasburgo-condanna-litalia_487a197c-b644-43ab-b287-479acb8a7a21.html",
    time: "2 ore fa",
    pub_ts: 1783301300,
    tags: [],
  },
  {
    id: 2,
    cat: "politica-italiana",
    title: "Trump posta meme con Meloni, 'necessaria ordinanza restrittiva'",
    summary: "Sul social Truth il nuovo attacco del presidente Usa alla premier italiana. Calenda: 'Bullo da quattro soldi'",
    body: "Sul social Truth il nuovo attacco del presidente Usa alla premier italiana. Calenda: 'Bullo da quattro soldi'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/mondo/nordamerica/2026/07/05/trump-posta-meme-con-la-meloni-necessaria-ordinanza-restrittiva_5c7d2e10-a87e-4318-a0cb-3fec90a74812.html",
    time: "6 ore fa",
    pub_ts: 1783288674,
    tags: [],
  },
  {
    id: 3,
    cat: "politica-italiana",
    title: "Gasolio oltre i 2 euro in autostrada. I consumatori: 'Una stangata prevista'",
    summary: "La polemica diventa politica, FdI contro il Codacons. Consumatori, in un anno +1,4 miliardi",
    body: "La polemica diventa politica, FdI contro il Codacons. Consumatori, in un anno +1,4 miliardi",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/economia/2026/07/05/il-gasolio-self-in-autostrada-torna-sopra-i-due-euro-al-litro_416bf39a-3bac-4b80-9c91-440c9dc374a1.html",
    time: "11 ore fa",
    pub_ts: 1783268353,
    tags: [],
  },
  {
    id: 4,
    cat: "politica-italiana",
    title: "L'Italia al top del turismo in Europa anche in estate",
    summary: "Arrivi in crescita nel primo semestre 2026. Mazzi: \"Settore strategico\"",
    body: "Arrivi in crescita nel primo semestre 2026. Mazzi: \"Settore strategico\"",
    source: "ANSA",
    url: "https://www.ansa.it/canale_viaggi/notizie/news/2026/07/05/litalia-al-top-del-turismo-in-europa-anche-in-estate_d454bf21-3779-4c3a-81ea-3514c585f848.html",
    time: "12 ore fa",
    pub_ts: 1783264383,
    tags: [],
  },
  {
    id: 5,
    cat: "politica-italiana",
    title: "Mondiali: Wsj 'gli italiani ignorano l'evento, è l'estate peggiore'",
    summary: "'L'assenza degli azzurri è un imbarazzo, anche nei bar tante tv spente'",
    body: "'L'assenza degli azzurri è un imbarazzo, anche nei bar tante tv spente'",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/sport/calcio/speciali/mondiale-calcio-2026/2026/07/05/mondiali-wsj-gli-italiani-ignorano-levento-e-lestate-peggiore-_e2adbb4c-420f-46b8-8b4a-0a7de483583c.html",
    time: "14 ore fa",
    pub_ts: 1783259936,
    tags: [],
  },
  {
    id: 6,
    cat: "politica-italiana",
    title: "All'Italian Global Series lo sceneggiatore Ridley: \"La discriminazione riguarda tutti, non basta essere preoccupati\"",
    summary: "Ha vinto un Oscar con \"12 anni schiavo\"",
    body: "Ha vinto un Oscar con \"12 anni schiavo\"",
    source: "ANSA",
    url: "https://www.ansa.it/sito/videogallery/spettacolo/2026/07/05/ridley-la-discriminazione-riguarda-tutti-non-basta-essere-preoccupati_6fc8fc2c-9576-44d5-8c9f-e3dbdfa09e19.html",
    time: "14 ore fa",
    pub_ts: 1783259628,
    tags: [],
  },
  {
    id: 7,
    cat: "politica-italiana",
    title: "Rita Pavone: 'Amo anticipare i tempi e lottare, tornerei anche a Sanremo'",
    summary: "Premiata all'Italian Global Series. L'11 luglio il marito Teddy Reno compie 100 anni",
    body: "Premiata all'Italian Global Series. L'11 luglio il marito Teddy Reno compie 100 anni",
    source: "ANSA",
    url: "https://www.ansa.it/sito/notizie/cultura/tv/2026/07/04/rita-pavone-amo-anticipare-i-tempi-e-lottare-tornerei-anche-a-sanremo_f68b6f86-1901-47c5-989b-49c8bea57b50.html",
    time: "20 ore fa",
    pub_ts: 1783237296,
    tags: [],
  },
  {
    id: 8,
    cat: "geopolitica",
    title: "Inglaterra termina con el sueño mundial de México",
    summary: "La selección de Tuchel se clasifica a cuartos gracias a dos golpes de Bellingham que pusieron cuesta arriba la epopeya de México",
    body: "Inglaterra puso fin al sueño mundial de México, el de la selección y todo un país, de la forma más cruel. El equipo de Tuchel, que aspira a todo, llega a cuartos con lo justo, gracias básicamente a dos mazazos seguidos de Bellingham en la primera parte que, a la postre, lastraron al equipo mexicano, al que no le bastó el tesón y el empuje de un Azteca inconmensurable. Hay partidos que terminan explicando la pasión por el fútbol.\n\nEste México-Inglaterra es uno de ellos. No solo porque definió uno de los mejores ocho equipos del Mundial, sino por la vibra que desprendía un estadio, un equipo, un deporte que, aunque fuera provisionalmente, ha alterado la manera en que millones de personas habitaron su propio país. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/mexico/2026-07-06/inglaterra-termina-con-el-sueno-mundial-de-mexico.html",
    time: "28 min fa",
    pub_ts: 1783309348,
    tags: [],
  },
  {
    id: 9,
    cat: "geopolitica",
    title: "Los cinco frentes abiertos que amenazan el futuro de la OTAN",
    summary: "Rusia, la hostilidad de Trump contra Europa, la crisis en Oriente Próximo o la guerra híbrida provocan grandes tensiones en una Alianza Atlántica que analiza a qué velocidad pueda cambiar sin romperse",
    body: "Hay organizaciones que envejecen despacio y otras a las que un solo año les cambia el rostro para siempre. A sus 77 años, la OTAN vive una transformación sustancial. Esta semana, en Ankara, los líderes de sus 32 miembros se sentarán con la misma pompa y ceremonia que llevan desplegando desde la Guerra Fría y que habla de “unidad inquebrantable”. Y, sin embargo, nada será igual. Detrás de los apretones de manos, la foto de familia y los contratos multimillonarios de armamento se libran cinco batallas simultáneas que explican la nueva realidad que amenaza la Alianza.\n\nLa casa construida en 1949 y que unía a Estados Unidos con la seguridad de Europa está aprendiendo, sin haberlo pedido, a separarse de la gran potencia. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-07-06/los-cinco-frentes-abiertos-que-amenazan-el-futuro-de-la-otan.html",
    time: "31 min fa",
    pub_ts: 1783309200,
    tags: [],
  },
  {
    id: 10,
    cat: "geopolitica",
    title: "La justicia francesa decide entre el todo o nada para Marine Le Pen",
    summary: "La histórica líder del ultraderechista Reagrupamiento Nacional afronta este martes una posible inhabilitación que dejaría al partido en manos de un dirigente ajeno a la familia",
    body: "El martes a las diez de la mañana, en una sala del Tribunal de Apelación de París, un juez dictará en voz alta la suerte del apellido que ha marcado la política en Francia en el último medio siglo. Marine Le Pen, líder del Reagrupamiento Nacional (RN), partido fundado por su padre en 1972 —entonces como Frente Nacional (FN)—, sabrá si es inhabilitada para todo cargo público y tiene que renunciar a su candidatura a las elecciones presidenciales de 2027: la cuarta, la ocasión en la que más cerca está de llegar al Elíseo, según todos los sondeos.\n\nUna decisión negativa marcará su carrera política, pero también el rumbo ideológico de su formación, que quedaría en manos del joven y todavía indescifrable Jordan Bardella. Una absolución, un atenuante al martirio judicial del que se ha proclamado víctima, la reforzaría ante los electores en una carrera en la que parte como clara favorita. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/internacional/2026-07-06/la-justicia-francesa-decide-entre-el-todo-o-nada-para-marine-le-pen.html",
    time: "31 min fa",
    pub_ts: 1783309200,
    tags: [],
  },
  {
    id: 11,
    cat: "geopolitica",
    title: "Asimetría de la justicia",
    summary: "La justicia no genera el consenso que se espera de una institución apolítica: donde la derecha ve neutralidad, la izquierda ve un activo del adversario",
    body: "La administración de Justicia suspende en confianza ciudadana, con un 4,9 sobre 10. Es una mala noticia para la democracia, pues se trata de uno de los pilares del Estado. Más grave aún es que ese suspenso se deba a las malas notas que le atribuyen las izquierdas: una institución apolítica debería generar consenso. De las cuatro instituciones del Estado incluidas en la encuesta de 40dB. , la Justicia es la única que la izquierda como bloque (PSOE, Sumar y Podemos) califica por debajo del aprobado, mientras que las derechas (PP y Vox) sí la aprueban.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-06/asimetria-de-la-justicia.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 12,
    cat: "geopolitica",
    title: "Ian Linnell: “El crecimiento en España podría ralentizarse si se echa el freno sobre la inmigración”",
    summary: "El presidente de la agencia Fitch avisa del riesgo de burbuja en los mercados financieros y cree que el impacto de la IA en el empleo será negativo a corto y medio plazo",
    body: "Es desde hace casi 10 años el máximo responsable de Fitch, una de las tres grandes agencias de calificación crediticia del mundo (las otras dos son Moody’s y S&amp;P), los árbitros mundiales que deciden cómo de solvente es una empresa, un banco o todo un país. No obstante, Ian Linnell (York, Reino Unido, 1967) rompe tópicos del sector financiero: conversador cercano, aficionado al ciclismo y con un marcado acento del norte de Inglaterra.\n\nPasa por Madrid y Barcelona dentro de las habituales rondas de contactos con clientes (las empresas pagan por recibir sus ratings) y, abrasado por el calor madrileño, confiesa que la conversación en las familias londinenses hoy gira en torno a la instalación de aire acondicionado. Desde su privilegiada atalaya, ve una economía mundial con señales de enfriamiento y riesgos en el sector financiero.\n\nAlgo que, insiste, tampoco nos debe asustar, pues la economía siempre ha operado en ciclos. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/economia/2026-07-06/ian-linnell-el-crecimiento-en-espana-podria-ralentizarse-si-se-echa-el-freno-sobre-la-inmigracion.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 13,
    cat: "geopolitica",
    title: "La lluvia de ceros en Euskera en la PAU vasca, en los tribunales: “Se está politizando”",
    summary: "Parte de los afectados, de seis colegios de Bilbao, sospechan que la corrección no fue anónima. La Universidad defiende la limpieza del proceso y apunta a un descenso del nivel",
    body: "La Prueba de Acceso a la Universidad (PAU) de 2026 en el País Vasco, a la que han concurrido 13.620 estudiantes, ha quedado marcada por la sorprendente multiplicación de ceros y suspensos registrados en el examen de Lengua Vasca y Literatura II. Un total de 168 jóvenes han sido calificados en primera instancia con un cero y han visto peligrar su acceso al grado que deseaban cursar en la universidad.\n\nHan salido a la calle a protestar porque sospechan que ha habido una mano negra en la corrección de los ejercicios de Euskera. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/educacion/universidad/2026-07-06/la-lluvia-de-ceros-en-euskera-en-la-pau-vasca-en-los-tribunales-se-esta-politizando.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 14,
    cat: "geopolitica",
    title: "Cristiano exprime su final ante Lamine el día que España busca los cuartos contra Portugal",
    summary: "El Mundial aguarda la eclosión definitiva del azulgrana en un cruce que puede ser el adiós de un mito: “Va a ser mi último Mundial; ojalá no sea mi último partido”",
    body: "La tarde que España se deshizo de Austria y se clasificó para los octavos de este lunes contra Portugal (21.00, La1 y Dazn), a Lamine Yamal se le vio contrariado mientras sostenía con cierta incomodidad el trofeo de mejor jugador del partido. El azulgrana ha venido al Mundial a llevarse la copa, pero también a seguir levantando la leyenda que se le adivina. Existen pocos escenarios como la Copa del Mundo para despertar el asombro, para volar a la cima, para hacerse admirar, e incluso para despedirse del olimpo.\n\nLa trayectoria del despegue de Lamine con 18 años se cruza en Dallas con el declinar de Cristiano Ronaldo, indesmayable a los 41. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-07-06/cristiano-exprime-su-final-ante-lamine-el-dia-que-espana-busca-los-cuartos-contra-portugal.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 15,
    cat: "geopolitica",
    title: "Madonna se hace un ‘revival’ de sí misma: solo la reina del pop se lo puede permitir",
    summary: "La artista publica ‘Confessions II’, la secuela de su disco de música ‘dance’ de hace más de dos décadas y se reivindica como un clásico en la época de las eras musicales",
    body: "Madonna ha publicado Confessions II , su disco número 15 , tras siete años sin un álbum y a punto de cumplir 68. Es la segunda parte de Confessions on a Dance Floor, trabajo que publicó en 2005, un homenaje a la música dance , a la que eleva la dopamina en la pista de baile, a lo que mejor sabe hacer, coinciden las críticas . Un tributo a sí misma en una época en la que el reguetón domina las listas de éxitos y los artistas tratan de reinventarse en cada trabajo.\n\nAhí están las Eras de Taylor Swift y los discos conceptuales de Rosalía , por poner dos ejemplos. “Madonna no lo necesita, se puede permitir jugar a ser un clásico y hacerse un revival de sí misma, eso no lo puede hacer prácticamente nadie”, afirma Eduardo Viñuela, musicólogo en la Universidad de Oviedo, especializado en música pop y urbana. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/cultura/2026-07-06/madonna-se-hace-un-revival-de-si-misma-solo-la-reina-del-pop-se-lo-puede-permitir.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 16,
    cat: "geopolitica",
    title: "Vitinha, el genio que mueve a Portugal, desafía a España en el duelo entre los dos centros del campo más extraordinarios del Mundial",
    summary: "El compás de la selección lusa, tercero en el último Balón de Oro por su influencia en el PSG, es el segundo pivote o volante que más pases da en el torneo tras Rodri",
    body: "Ni siquiera echó una sonrisa cuando compareció el pasado miércoles en Toronto y los periodistas le mencionaron a su ídolo. El rictus de Vítor Machado, Vitinha , aguantó hierático, inexpresivo pese a las preguntas sobre qué significaba para él volver a enfrentarse una vez más con Luka Modric. El mediocentro de 26 años despachó con aires burocráticos la cuestión y se refirió a lo que de verdad necesitaba Portugal para tumbar a Croacia en los dieciseisavos del Mundial.\n\n“Él es una gran referencia para mí, ya hablé de esto y ya me cambié la camiseta con él [en el Mundial de Clubes 2025]. Lo importante es que nuestra mejora como equipo tiene que ser colectiva, tenemos muchos aspectos que mejorar”, soltó. Al día siguiente, la Seleção tumbó al combinado del país balcánico (2-1) tras remontar el gol de Perisic con un penalti de Cristiano y un tanto de Gonçalo Ramos en el 93.\n\nOtra vez más, la función del equipo dirigido por Roberto Martínez generó dudas sobre un engranaje que a veces se engrasa y otras se trastabilla. El jugador de Santo Tirso, el hombre que ocupó el tercer escalón del podio del último Balón de Oro y que mueve al PSG bicampeón de la Champions, sabe mejor que nadie que la maquinaria de Portugal tendrá que estar todavía más afinada este lunes ante España (21.00; La1 y Dazn) en Dallas en el duelo entre los dos centros del campo más extraordinarios del torneo.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-07-06/vitinha-el-genio-que-mueve-a-portugal-desafia-a-espana-en-el-duelo-entre-los-dos-centros-del-campo-mas-extraordinarios-del-mundial.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 17,
    cat: "geopolitica",
    title: "Más del 65% considera que el ‘lawfare’ existe en España",
    summary: "Los casos que afectan al PSOE son más conocidos que los que involucran al PP. Una de cada tres personas cree que los jueces tienden a favorecer a la derecha",
    body: "A los españoles les cuesta confiar en su sistema judicial en un momento en el que los tribunales acaparan la agenda y el debate público por la acumulación de escándalos de corrupción. Así lo pone en evidencia el estudio del Instituto 40dB. para EL PAÍS y la Cadena SER monográfico sobre la Justicia. La mayoría (82%) piensa que es “demasiado lenta” y poco independiente: Solo el 32% cree que las resoluciones sobre asuntos políticos son justas e imparciales; el 65,4% considera que en España existe lawfare [guerra judicial] y casi un 60% cree que el poder judicial vigila y sanciona poco o nada a los jueces que hacen mal su trabajo.\n\nSeguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-06/mas-del-65-considera-que-el-lawfare-existe-en-espana.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 18,
    cat: "geopolitica",
    title: "Dormir en verano: La ciencia del sueño roto por el calor",
    summary: "Las noches tropicales alteran el descanso profundo, dañan la memoria y anticipan un futuro en el que cada persona perderá más de 50 horas de sueño al año por las altas temperaturas",
    body: "Despertarse en mitad de la noche, apartar la sábana con el pie, girar de un lado a otro en busca de un rincón más fresco del colchón. Esta molesta coreografía estival se ha convertido en un problema que avanza sobre la salud pública mundial. La falta de sueño no solo se vive en la piel, también se infiltra en la arquitectura íntima del cuerpo y desordena los sistemas que sostienen la memoria, la estabilidad emocional y la regulación fisiológica del organismo.\n\nEl año pasado, España experimentó niveles históricos en la frecuencia e intensidad de las noches calurosas. Y para finales de siglo, las proyecciones apuntan a un escenario en el que, a nivel global, cada persona perderá más de 50 horas de descanso al año . Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/salud-y-bienestar/2026-07-06/dormir-en-verano-la-ciencia-del-sueno-roto-por-el-calor.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 19,
    cat: "geopolitica",
    title: "¿Serán limpias las elecciones de noviembre en EE UU?",
    summary: "He dedicado mi carrera a perseguir a dictadores y a documentar cómo se degradan las democracias: lo que ocurre en mi país es un patrón que conozco bien",
    body: "Las elecciones de mitad de mandato siempre han sido una prueba importante para cualquier presidente de los Estados Unidos. Funcionan como un referéndum sobre el poder en ejercicio y, a menudo, corrigen el rumbo político del país. Pero las del próximo 3 de noviembre tienen una importancia distinta. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-06/seran-limpias-las-elecciones-de-noviembre-en-ee-uu.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 20,
    cat: "geopolitica",
    title: "Nicolás Sartorius: “La derecha que viene no es la derecha de siempre, este PP no es heredero de la Transición”",
    summary: "“La prioridad nacional sustituye el principio de ciudadanía en el que está basada la democracia por el de la identidad, que es típica de los regímenes autoritarios y xenófobos”, advierte el referente de la izquierda y la lucha por la democracia",
    body: "Nicolás Sartorius (San Sebastián, 88 años), histórico referente de la izquierda y de la lucha por la democracia que pasó seis años en las cárceles franquistas, alerta de la crispación excepcional de la política española, con el Gobierno cercado por el frente judicial mientras Alberto Núñez Feijóo liga su destino al de Vox. El cofundador de Comisiones Obreras advierte que ningún Ejecutivo ha soportado el mismo nivel de insultos y ataques que el de Pedro Sánchez desde la restauración de la democracia.\n\nY avisa de la transformación que a su juicio está experimentando el PP tras asumir la prioridad nacional y otras banderas de la ultraderecha. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-06/nicolas-sartorius-la-derecha-que-viene-no-es-la-derecha-de-siempre-este-pp-no-es-heredero-de-la-transicion.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 21,
    cat: "geopolitica",
    title: "El sector del ‘lobby’ reclama la “aprobación urgente” de una ley para regular su actividad",
    summary: "La imputación de Zapatero por tráfico de influencias exige una norma “clara, ambiciosa y eficaz” para trabajar",
    body: "“¿Dónde acaba y empieza el tráfico de influencias?” , se preguntaba el pasado mayo el portavoz de ERC, Gabriel Rufián , tras la imputación del expresidente del Gobierno José Luis Rodríguez Zapatero por, presuntamente, influir ilegalmente en el rescate de la aerolínea venezolana Plus Ultra . Los profesionales del sector del lobby —dedicados a influir las legislaciones y decisiones políticas en favor de determinadas empresas, colectivos y organizaciones— llevan años pidiendo una ley que establezca de forma “clara, ambiciosa y eficaz” la línea entre la legalidad y el tráfico de influencias.\n\nEl martes pasado, la Asociación de Profesionales de las Relaciones Institucionales (APRI) envió decenas de cartas a los miembros de la Mesa de la Cámara Baja y a los principales líderes y portavoces de los grupos parlamentarios para reclamar la “aprobación urgente” de una regulación que lleva años estancada. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-06/el-sector-del-lobby-reclama-la-aprobacion-urgente-de-una-ley-para-regular-su-actividad.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 22,
    cat: "geopolitica",
    title: "Solomy Balungi Bossa, jueza del Tribunal Penal Internacional: “Para Trump somos como los terroristas o narcotraficantes”",
    summary: "La ugandesa, de 70 años, es una de las magistradas del TPI sancionadas por EEUU por investigaciones que afectaban a ese país y a Israel",
    body: "La ugandesa Solomy Balungi Bossa, de 70 años, jueza de apelaciones en el Tribunal Penal Internacional (TPI), es una de las sancionadas por Donald Trump por llevar a cabo investigaciones relacionadas con EEUU e Israel. Acaba de participar en un coloquio en Madrid junto al exmagistrado de la Audiencia Nacional Baltasar Garzón y el eurodiputado socialista Juan Fernando López Aguilar. El acto forma parte de la campaña organizada por el movimiento Eumans y No Peace Without Justice apoyada por seis premios Nobel para defender la labor de la justicia internacional.\n\nAntes de ingresar en el TPI en 2018, con un mandato de nueve años, Bossa trabajó en el tribunal de Naciones Unidas para Ruanda. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/espana/2026-07-06/solomy-balungi-bossa-jueza-del-tribunal-penal-internacional-para-trump-somos-como-los-terroristas-o-narcotraficantes.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 23,
    cat: "geopolitica",
    title: "Cuando todo se complica, Álex Baena",
    summary: "“Hay jugadores de selección”, elogia De la Fuente a un hombre acostumbrado a superar adversidades",
    body: "En las difíciles, Álex Baena. Hay talentos llamados a tocar las puertas del cielo en los momentos complicados. Por ejemplo, cuando todo se complica en el escaparate más exclusivo del fútbol, un Mundial. De la Fuente lo tiene claro: “Hay jugadores que son de selección”. Después del fallido experimento de colocar a Gavi como extremo para reemplazar a Nico Williams —el domingo realizó casi todo el entrenamiento junto a sus compañeros—, Baena se instaló en el ala izquierda de España.\n\nY ya nadie lo movió. Jugó frente a Arabia, marcó ante Uruguay y asistió contra Austria. Ahora apunta contra la Portugal de Cristiano. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/deportes/mundial-futbol/2026-07-06/cuando-todo-se-complica-alex-baena.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 24,
    cat: "geopolitica",
    title: "El espejo finlandés",
    summary: "La demanda de maestras españolas en Finlandia, un reconocimiento del valor de las docentes, también evidencia las insuficientes condiciones laborales en España",
    body: "Ni el idioma, famosamente complicado para el hispanohablante, ni un clima inhóspito en algunas épocas del año, ni tampoco un coste de la vida más elevado que en España han disuadido a las maestras que en los últimos meses han decidido hacer las maletas e instalarse en Finlandia. El Ayuntamiento de Helsinki ha acelerado un plan para atraer a docentes de educación infantil del resto de Europa con el fin de suplir una carencia de unos 6.000 educadores.\n\nY así ha dado un ejemplo práctico sobre cómo atraer talento y valorar como merecen a estas educadoras, fundamentales en los primeros pasos de la formación de los futuros ciudadanos. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-06/el-espejo-finlandes.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 25,
    cat: "geopolitica",
    title: "Los castigos de Milei",
    summary: "Hay que desconfiar de las noticias que hablan de justicia pero apelan a nuestro instinto de venganza, porque el fascismo vive de este",
    body: "El sistema de crédito social chino fue un experimento que despertó gran fascinación en Occidente porque, más que un sistema de vigilancia, era un proyecto de reeducación. Buscaba corregir “vicios” de la ciudadanía como comprar alcohol, faltar al trabajo, cruzar en rojo, no visitar a los padres ancianos y, por supuesto, participar en manifestaciones o criticar al gobierno en el chat familiar. Estaba perfectamente alineado con la era del me gusta : cada ciudadano empezaba con 400 puntos y el correctivo por perderlos era ir limitando su acceso a productos y servicios importantes, incluyendo el parque de viviendas, puestos de trabajo y buenos colegios para sus hijos, pero también billetes de avión, de tren y hasta de autobús.\n\nSu eslogan lo decía todo: los buenos ciudadanos caminarán libres bajo el sol y los malos ciudadanos no podrán dar un paso. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-06/los-castigos-de-milei.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 26,
    cat: "geopolitica",
    title: "El trauma del 23-J",
    summary: "Es posible que Alberto Núñez Feijóo esté sufriendo un desgaste insólito y autoinducido en lo que habría de ser un tránsito seguro hacia La Moncloa",
    body: "No hace falta ser un freudiano de estricta observancia para reconocer la influencia de los traumas. Las personas, los países y las organizaciones están expuestos a impactos emocionales que operan de forma inconsciente y que determinan la manera en la que vivimos y nos pensamos. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-06/el-trauma-del-23-j.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 27,
    cat: "geopolitica",
    title: "Y la empatía también se transformó en trinchera",
    summary: "La derecha radical, con el apoyo de los tecnooligarcas, dice que ser justos, compasivos y solidarios es de débiles",
    body: "Gaza es uno de los cementerios infantiles más grandes del mundo. Según datos de Unicef, al menos 21.000 pequeños han muerto desde el 7 de octubre de 2023 , fecha del horrible atentado de Hamás que animó a Benjamin Netanyahu a emplearse a fondo en firmar un genocidio moderno. Hace algunos días veinte de los niños palestinos que han logrado sobrevivir aterrizaron en Madrid acompañados de sus familias para ser tratados de distintas patologías en hospitales de Madrid, Santander, Oviedo, Murcia, Vitoria y Toledo.\n\nLa ministra de Sanidad, Mónica García, documentó con algunas fotos la llegada del avión desde su cuenta personal de X. “Dejan atrás la barbarie para recibir la atención que necesitan en nuestros hospitales. Llegan con miedo, pero también con esperanza. Orgullo de país”. Seguir leyendo",
    source: "El Pais",
    url: "https://elpais.com/opinion/2026-07-06/y-la-empatia-tambien-se-transformo-en-trinchera.html",
    time: "41 min fa",
    pub_ts: 1783308601,
    tags: [],
  },
  {
    id: 28,
    cat: "conflitti",
    title: "OPEC+ countries say they will expand monthly oil production",
    summary: "Seven OPEC+ members, including Saudi Arabia and Russia, to increase output by 188,000 barrels per day.",
    body: "Seven OPEC+ members, including Saudi Arabia and Russia, to increase output by 188,000 barrels per day.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/economy/2026/7/6/opec-countries-say-they-will-expand-monthly-oil-production?traffic_source=rss",
    time: "1 ora fa",
    pub_ts: 1783307046,
    tags: [],
  },
  {
    id: 29,
    cat: "conflitti",
    title: "How conflict minerals fuel war in eastern DR Congo amid US sanctions",
    summary: "The move underscores growing scrutiny of the conflict mineral trade fuelling violence in eastern DR Congo.",
    body: "The move underscores growing scrutiny of the conflict mineral trade fuelling violence in eastern DR Congo.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/6/us-sanctions-target-rwandan-firms-linked-to-conflict-minerals-funding-m23?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1783303837,
    tags: [],
  },
  {
    id: 30,
    cat: "conflitti",
    title: "Tuareg fighters claim to have shot down a Russian helicopter in Mali",
    summary: "Tuareg fighters in Mali have released footage claiming to have shot down a Russian Africa Corps Mi-24 helicopter.",
    body: "Tuareg fighters in Mali have released footage claiming to have shot down a Russian Africa Corps Mi-24 helicopter.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/7/6/aje-onl-nf_mali-rebels-claim-to-have-shot-down-russian-helicop-050726?traffic_source=rss",
    time: "2 ore fa",
    pub_ts: 1783301717,
    tags: [],
  },
  {
    id: 31,
    cat: "conflitti",
    title: "Iran war live: Tehran prepares for Ali Khamenei’s funeral procession",
    summary: "Millions expected at funeral procession for Iran&#039;s slain supreme leader in Tehran today.",
    body: "Millions expected at funeral procession for Iran&#039;s slain supreme leader in Tehran today.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/liveblog/2026/7/6/iran-war-live-tehran-set-for-khameneis-procession-israel-bombs-lebanon?traffic_source=rss",
    time: "4 ore fa",
    pub_ts: 1783296000,
    tags: [],
  },
  {
    id: 32,
    cat: "conflitti",
    title: "Palestinian baby dies in West Bank after Israel blocks urgent medical care",
    summary: "Israeli forces also shoot dead a 16-year-old boy in the occupied West Bank and kill two Palestinians in Gaza.",
    body: "Israeli forces also shoot dead a 16-year-old boy in the occupied West Bank and kill two Palestinians in Gaza.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/7/5/palestinian-baby-dies-in-west-bank-after-israel-blocks-urgent-medical-care?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1783289032,
    tags: [],
  },
  {
    id: 33,
    cat: "conflitti",
    title: "Turkiye gears up for its first NATO summit in 22 years",
    summary: "Leaders of the NATO member states are expected in Turkiye by July 7 for a summit - the first it will host in 22 years.",
    body: "Leaders of the NATO member states are expected in Turkiye by July 7 for a summit - the first it will host in 22 years.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/video/newsfeed/2026/7/5/turkiye-gears-up-for-its-first-nato-summit-in-22-years?traffic_source=rss",
    time: "6 ore fa",
    pub_ts: 1783287768,
    tags: [],
  },
  {
    id: 34,
    cat: "ai",
    title: "Some of the nation’s rich are letting AI teach their kids",
    summary: "Most Americans don't trust AI. It's proven that it doesn't know what safe toppings for pizza are. People don't even want to listen to AI music. But none of that matters for some of America's wealthy, who are turning to AI to teach their kids instead of traditional schools. Companies like Forge Prep and Alpha [&#8230;]",
    body: "Most Americans don't trust AI . It's proven that it doesn't know what safe toppings for pizza are. People don't even want to listen to AI music . But none of that matters for some of America's wealthy, who are turning to AI to teach their kids instead of traditional schools. Companies like Forge Prep and Alpha School are charging families tens of thousands of dollars to turn their kids into beta testers for AI tutors and \"interactive project-based workshops.\" Unsurprisingly, Silicon Valley have been major adopters of this new model.\n\nShaun Johnson, a San Francisco-based venture capitalist, told the Wall Street Journal that he plans to send his …",
    source: "The Verge",
    url: "https://www.theverge.com/ai-artificial-intelligence/961505/wealthy-ai-schools-alpha-forge-prep",
    time: "5 ore fa",
    pub_ts: 1783290654,
    tags: [],
  },
  {
    id: 35,
    cat: "ai",
    title: "Uber’s European expansion plans may have hit a speed bump",
    summary: "Back in February, Uber announced ambitious plans to launch in seven new European markets in 2026 — but now five of those launches are reportedly on hold.",
    body: "Back in February, Uber announced ambitious plans to launch in seven new European markets in 2026 — but now five of those launches are reportedly on hold.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/05/ubers-european-expansion-plans-may-have-hit-a-speed-bump/",
    time: "6 ore fa",
    pub_ts: 1783287317,
    tags: [],
  },
  {
    id: 36,
    cat: "ai",
    title: "Trump memecoin investors lost $3.8 billion, analysis finds",
    summary: "Nearly 1 million people have lost a total of $3.8 billion after buying President Donald Trump’s $TRUMP memecoin, while Trump made $636 million.",
    body: "Nearly 1 million people have lost a total of $3.8 billion after buying President Donald Trump’s $TRUMP memecoin, while Trump made $636 million.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/05/trump-memecoin-investors-lost-3-8-billion-analysis-finds/",
    time: "7 ore fa",
    pub_ts: 1783283345,
    tags: [],
  },
  {
    id: 37,
    cat: "ai",
    title: "Mr. Lif’s Emergency Rations EP is post-9/11 hip hop at its most daring",
    summary: "There was a period in the early aughts when Definitive Jux (nee: Def Jux) seemed like it was going to be the future of hip hop. While the label featured plenty of experimental, boundary-pushing, and politically minded acts, Lif stood out as the most \"conscious rapper\" in the traditional sense. It was clear though, that [&#8230;]",
    body: "First, you drop bombs, then you send aid. Totally logical. | Image: Definitive Jux There was a period in the early aughts when Definitive Jux (nee: Def Jux) seemed like it was going to be the future of hip hop. While the label featured plenty of experimental, boundary-pushing, and politically minded acts, Lif stood out as the most \"conscious rapper\" in the traditional sense. It was clear though, that label head El-P envisioned that as an important part of Def Jux's identity, as the first record it put out was 2000's Enter the Colossus EP, from Lif.\n\nMr. Lif's follow-up was 2002's Emergency Rations EP, a sort of place setter for the full-length I, Phantom just a couple of months later. It opens with a skit about Lif missing …",
    source: "The Verge",
    url: "https://www.theverge.com/entertainment/961484/mr-lif-emergency-rations-ep-post-9-11-review",
    time: "9 ore fa",
    pub_ts: 1783276200,
    tags: [],
  },
  {
    id: 38,
    cat: "ai",
    title: "Amazon will stop accepting new customers for Mechanical Turk",
    summary: "These may be the last days of Amazon’s Mechanical Turk.",
    body: "These may be the last days of Amazon’s Mechanical Turk.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/05/amazon-will-stop-accepting-new-customers-for-mechanical-turk/",
    time: "10 ore fa",
    pub_ts: 1783273416,
    tags: [],
  },
  {
    id: 39,
    cat: "ai",
    title: "Where to preorder Grand Theft Auto VI",
    summary: "Rockstar's long-awaited Grand Theft Auto VI is launching November 19th, 2026 for PlayStation 5 and Xbox Series S/X consoles. The game will be available digitally at launch, with physical cases containing codes, not discs, so your options for preordering are straightforward. The preloading phase for the game begins on November 12th, which should give you [&#8230;]",
    body: "A look at in-game cosmetics you’ll get with the Ultimate edition. | Image: Rockstar Games Rockstar's long-awaited Grand Theft Auto VI is launching November 19th, 2026 for PlayStation 5 and Xbox Series S/X consoles. The game will be available digitally at launch, with physical cases containing codes, not discs , so your options for preordering are straightforward. The preloading phase for the game begins on November 12th, which should give you plenty of time to install the game.\n\nThere are two versions of the game to choose from, the $79.99 Standard and $99.99 Ultimate editions. Both include the same preorder perks. You'll get the Vintage Vice City Pack when the game launches. It's a set of in-game items that includes vehicles, we …",
    source: "The Verge",
    url: "https://www.theverge.com/gadgets/960838/grand-theft-auto-gta-6-vi-preorder-editions-buy",
    time: "12 ore fa",
    pub_ts: 1783267200,
    tags: [],
  },
  {
    id: 40,
    cat: "ai",
    title: "5 desk gadgets that can make your workday better",
    summary: "The right desk gadgets can help you reduce clutter, stay focused, and add a little extra convenience to your day.",
    body: "The right desk gadgets can help you reduce clutter, stay focused, and add a little extra convenience to your day.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/05/5-desk-gadgets-that-can-make-your-workday-better/",
    time: "13 ore fa",
    pub_ts: 1783263600,
    tags: [],
  },
  {
    id: 41,
    cat: "ai",
    title: "Infuriating Google commercial imagines the founding fathers embracing AI",
    summary: "\"Group project, but make it 1776.\" That's how a new commercial for Google Workspace opens. And things only get cringier from there. The clip imagines what it would be like if the founding fathers turned to Google's collaboration tools and Gemini to help them draft the Declaration of Independence. Ben Franklin texts Thomas Jefferson to [&#8230;]",
    body: "I call BS: the founding fathers definitely would have been Microsoft Teams users. | Image: Google \"Group project, but make it 1776.\" That's how a new commercial for Google Workspace opens. And things only get cringier from there. The clip imagines what it would be like if the founding fathers turned to Google's collaboration tools and Gemini to help them draft the Declaration of Independence. Ben Franklin texts Thomas Jefferson to check on the status of a draft, who takes a photo and uses AI to transcribe it into a Google Doc.\n\nFranklin and Adams hop in to make edits in suggestion mode, Gemini finds them a meeting time, takes notes during a Google Meet call, and then Nano Banana whips up a seal for the United States featuring a turkey ( …",
    source: "The Verge",
    url: "https://www.theverge.com/ai-artificial-intelligence/961468/google-ai-commercial-founding-fathers-declaration-of-independence",
    time: "13 ore fa",
    pub_ts: 1783261391,
    tags: [],
  },
  {
    id: 42,
    cat: "ai",
    title: "The Sourdough Sidekick automates the boring bit of baking",
    summary: "Baking sourdough bread is inherently old-fashioned, relying on natural fermentation and wild yeast instead of the simple, predictable commercial stuff. So it might sound anathema to bring a gadget into the mix. The trick to the Sourdough Sidekick - backed and branded by King Arthur flour - is that it promises to automate the boring [&#8230;]",
    body: "The Sourdough Sidekick was codeveloped with King Arthur Baking Company. Baking sourdough bread is inherently old-fashioned, relying on natural fermentation and wild yeast instead of the simple, predictable commercial stuff. So it might sound anathema to bring a gadget into the mix. The trick to the Sourdough Sidekick - backed and branded by King Arthur flour - is that it promises to automate the boring bit of sourdough baking: starter management.\n\nIt feeds your starter flour and water on a set schedule, ready for exactly when you want to bake, leaving you to focus on kneading, shaping, and the actual baking. Like any single-purpose kitchen gadget, you'll have to be confident you'll get enough use to justify b …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/959604/sourdough-sidekick-review-king-arthur-starter",
    time: "14 ore fa",
    pub_ts: 1783260000,
    tags: [],
  },
  {
    id: 43,
    cat: "ai",
    title: "How Keurig saved — and ruined — your coffee",
    summary: "Before Keurig, the coffee in your office was almost certainly terrible. Old, burned, made by someone who would rather poorly eyeball than properly measure. Just altogether gross. After Keurig? You could make your own coffee, a cup at a time, exactly when you needed it. The single-cup brewer was an elegant solution to an extremely [&#8230;]",
    body: "Before Keurig, the coffee in your office was almost certainly terrible. Old, burned, made by someone who would rather poorly eyeball than properly measure. Just altogether gross. After Keurig? You could make your own coffee, a cup at a time, exactly when you needed it. The single-cup brewer was an elegant solution to an extremely common problem. At least, that's how it started. On this episode of Version History , we dig into the history of the Keurig, and the ways in which the idea got vastly bigger than anyone expected.\n\nK-Cups and Keurig machines became ubiquitous in offices all across the US, then quickly began to invade our homes as well …",
    source: "The Verge",
    url: "https://www.theverge.com/podcast/961470/keurig-coffee-k-up-version-history",
    time: "14 ore fa",
    pub_ts: 1783259516,
    tags: [],
  },
  {
    id: 44,
    cat: "ai",
    title: "What is Bending Spoons? The little-known AOL and Vimeo owner that’s now public",
    summary: "Bending Spoons remains largely unknown, even as its portfolio of products has served more than a billion people.",
    body: "Bending Spoons remains largely unknown, even as its portfolio of products has served more than a billion people.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/05/what-is-bending-spoons-everything-to-know-about-aols-acquirer/",
    time: "14 ore fa",
    pub_ts: 1783258412,
    tags: [],
  },
  {
    id: 45,
    cat: "ai",
    title: "Vizio accidentally made the best dumb TV on the market",
    summary: "When I first started testing Vizio's 65-inch Mini LED Quantum TV, I thought the big story was that Vizio was back and that it had a quantum-dot TV for under $398 - the cheapest on the market. Vizio's been pretty quiet since it was acquired by Walmart in 2024, so putting out a TV with [&#8230;]",
    body: "Vizio OS works well, but you don’t even need to use it. When I first started testing Vizio's 65-inch Mini LED Quantum TV, I thought the big story was that Vizio was back and that it had a quantum-dot TV for under $398 - the cheapest on the market. Vizio's been pretty quiet since it was acquired by Walmart in 2024, so putting out a TV with quantum dots, which allow for higher brightness levels and more accurate color, at a budget price seemed like a strong comeback.\n\nBut that's not the big story. While those two points are intriguing, the big news about the Mini LED Quantum TV is that Vizio accidentally made the best dumb TV on the market. Vizio Mini LED Quantum TV Where to Buy: $398 at Walmart ( …",
    source: "The Verge",
    url: "https://www.theverge.com/tech/960916/vizio-mini-led-quantum-tv-review",
    time: "15 ore fa",
    pub_ts: 1783256400,
    tags: [],
  },
  {
    id: 46,
    cat: "ai",
    title: "Almost 90 new unicorns have been minted so far this year — here they are",
    summary: "With AI igniting an investor frenzy, more startups are achieving unicorn status every month.",
    body: "With AI igniting an investor frenzy, more startups are achieving unicorn status every month.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/05/almost-40-new-unicorns-have-been-minted-so-far-this-year-here-they-are/",
    time: "15 ore fa",
    pub_ts: 1783255659,
    tags: [],
  },
  {
    id: 47,
    cat: "ai",
    title: "Xbox is a disaster",
    summary: "This is The Stepback, a weekly newsletter breaking down one essential story from the tech world. For more on the bleak state of the video game industry, follow Andrew Webster. The Stepback arrives in our subscribers' inboxes on Sunday at 8AM ET. Opt in for The Stepback here. How it started Microsoft closed out Summer [&#8230;]",
    body: "Gears of War: E-Day. This is The Stepback , a weekly newsletter breaking down one essential story from the tech world. For more on the bleak state of the video game industry, follow Andrew Webster . The Stepback arrives in our subscribers' inboxes on Sunday at 8AM ET. Opt in for The Stepback here . How it started Microsoft closed out Summer Game Fest with a bang. The company's annual June showcase was packed with crowd-pleasers: Halo , Gears of War , Fable , a translucent Xbox, and even some pleasant surprises like new Persona and Crazy Taxi games.\n\nIt was the kind of event that harkened back to the boisterous days of E3, when the industry was in a healthier place an …",
    source: "The Verge",
    url: "https://www.theverge.com/column/960600/xbox-is-a-disaster",
    time: "16 ore fa",
    pub_ts: 1783252800,
    tags: [],
  },
  {
    id: 48,
    cat: "ai",
    title: "A cosa dovrebbero servirci gli occhiali smart?",
    summary: "In commercio ce ne sono sempre più modelli, ma non abbiamo ancora capito per quali funzioni abbiano davvero senso",
    body: "In commercio ce ne sono sempre più modelli, ma non abbiamo ancora capito per quali funzioni abbiano davvero senso",
    source: "Il Post Tech",
    url: "https://www.ilpost.it/2026/07/05/senso-occhiali-smart/",
    time: "19 ore fa",
    pub_ts: 1783239661,
    tags: [],
  },
  {
    id: 49,
    cat: "ai",
    title: "New Google commercial imagines a Declaration of Independence written with help from AI",
    summary: "Two hundred and fifty years after the signing of the Declaration of Independence, a new commercial asks: What if the Founding Fathers had access to Google Workspace?",
    body: "Two hundred and fifty years after the signing of the Declaration of Independence, a new commercial asks: What if the Founding Fathers had access to Google Workspace?",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/04/new-google-commercial-imagines-a-declaration-of-independence-written-with-help-from-ai/",
    time: "1 giorno fa",
    pub_ts: 1783198525,
    tags: [],
  },
  {
    id: 50,
    cat: "ai",
    title: "NASA launched an emergency mission to stop the Swift Observatory from crashing to Earth",
    summary: "The Swift Observatory was launched in 2004, but recent solar storms have pushed its orbit lower, and it's in danger of burning up in Earth's atmosphere as soon as this year. To try and stave off its demise, NASA has enlisted Katalyst Space Technologies. The company's Link spacecraft launched Friday with the goal of intercepting [&#8230;]",
    body: "Engineers from Katalyst Space Technologies testing Link. | Image: NASA/Scott Wiessinger The Swift Observatory was launched in 2004, but recent solar storms have pushed its orbit lower, and it's in danger of burning up in Earth's atmosphere as soon as this year. To try and stave off its demise , NASA has enlisted Katalyst Space Technologies. The company's Link spacecraft launched Friday with the goal of intercepting Swift, which has no propulsion system, and boosting its orbit back to its original position.\n\nRight now, Swift is circling at an altitude of 224 miles, and Link is aiming to raise that by about 150 miles. Using a three-armed spacecraft to lift a satellite 150 miles higher into orbit is challenging enough, but the spee …",
    source: "The Verge",
    url: "https://www.theverge.com/science/961459/nasa-emergency-save-swift-observatory-katalyst-space-technologies",
    time: "1 giorno fa",
    pub_ts: 1783191987,
    tags: [],
  },
  {
    id: 51,
    cat: "ai",
    title: "Midjourney wants Hollywood studios to reveal the details of their AI usage",
    summary: "As part of an ongoing legal dispute with three Hollywood studios, Midjourney is seeking to compel those studios to reveal how they use AI themselves.",
    body: "As part of an ongoing legal dispute with three Hollywood studios, Midjourney is seeking to compel those studios to reveal how they use AI themselves.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/04/midjourney-wants-hollywood-studios-to-reveal-the-details-of-their-ai-usage/",
    time: "1 giorno fa",
    pub_ts: 1783188005,
    tags: [],
  },
  {
    id: 52,
    cat: "ai",
    title: "Alibaba reportedly bans employees from using Claude Code",
    summary: "Alibaba has reportedly classified Claude Code as high-risk software.",
    body: "Alibaba has reportedly classified Claude Code as high-risk software.",
    source: "TechCrunch",
    url: "https://techcrunch.com/2026/07/04/alibaba-reportedly-bans-employees-from-using-claude-code/",
    time: "1 giorno fa",
    pub_ts: 1783182728,
    tags: [],
  },
  {
    id: 53,
    cat: "ai",
    title: "White House deletes thousands of web pages about energy conservation as heatwave slams US",
    summary: "The US Department of Energy reportedly deleted about 6,000 pages related to energy conservation as a historic heatwave tears across the country. The deletion was suspiciously timed, following Republican outrage over Mayor Zohran Mamdani asking New Yorkers to help reduce strain on the grid by setting their AC to 78 degrees. Republicans like Ted Cruz [&#8230;]",
    body: "The US Department of Energy reportedly deleted about 6,000 pages related to energy conservation as a historic heatwave tears across the country. The deletion was suspiciously timed, following Republican outrage over Mayor Zohran Mamdani asking New Yorkers to help reduce strain on the grid by setting their AC to 78 degrees . Republicans like Ted Cruz (who has famously fled severe weather in his home state), Nikki Haley, and Representative Nancy Mace (South Carolina) quickly pounced , framing the request as socialism and an act of war on women in menopause (the Republican Party is notoriously concerned about women's health).\n\nOf course, this i …",
    source: "The Verge",
    url: "https://www.theverge.com/policy/961449/white-house-mamdani-heatwave-deletion",
    time: "1 giorno fa",
    pub_ts: 1783181946,
    tags: [],
  },
  {
    id: 54,
    cat: "economia-tech",
    title: "Why OpenAI and Anthropic may struggle to float",
    summary: "The costs of remaining at the frontier of AI are punishing, but the penalties for falling behind may be even worse",
    body: "The costs of remaining at the frontier of AI are punishing, but the penalties for falling behind may be even worse",
    source: "Financial Times",
    url: "https://www.ft.com/content/7bff5ad3-a7dc-4641-be97-7f383446ff75",
    time: "10 min fa",
    pub_ts: 1783310423,
    tags: [],
  },
  {
    id: 55,
    cat: "economia-tech",
    title: "Andy Burnham needs to start by understanding how little he knows",
    summary: "Even if he could do all he wants, it would be unlikely to solve the UK’s growth problem",
    body: "Even if he could do all he wants, it would be unlikely to solve the UK’s growth problem",
    source: "Financial Times",
    url: "https://www.ft.com/content/e21fde74-724f-4898-a382-88cbac975a12",
    time: "10 min fa",
    pub_ts: 1783310423,
    tags: [],
  },
  {
    id: 56,
    cat: "economia-tech",
    title: "Big investors commit billions to private credit despite turmoil",
    summary: "Institutional investors poured money into funds as retail money fled",
    body: "Institutional investors poured money into funds as retail money fled",
    source: "Financial Times",
    url: "https://www.ft.com/content/ea275bbd-e411-4db5-a9d2-415666f2a923",
    time: "10 min fa",
    pub_ts: 1783310422,
    tags: [],
  },
  {
    id: 57,
    cat: "economia-tech",
    title: "How modern drone warfare is forcing arms producers to rethink",
    summary: "UK start-up Isembard is linking hundreds of small machine shops into a decentralised military manufacturing network",
    body: "UK start-up Isembard is linking hundreds of small machine shops into a decentralised military manufacturing network",
    source: "Financial Times",
    url: "https://www.ft.com/content/f67994f3-b3ef-4a94-a70e-29c5263a3cc3",
    time: "10 min fa",
    pub_ts: 1783310422,
    tags: [],
  },
  {
    id: 58,
    cat: "economia-tech",
    title: "Shipowners turn to dirty fossil fuels and nuclear power as green hopes sail away",
    summary: "Deeply divided industry fractures into several camps backing different technologies and fuels",
    body: "Deeply divided industry fractures into several camps backing different technologies and fuels",
    source: "Financial Times",
    url: "https://www.ft.com/content/2eb36e45-68de-4510-bec1-73da9db98480",
    time: "10 min fa",
    pub_ts: 1783310413,
    tags: [],
  },
  {
    id: 59,
    cat: "economia-tech",
    title: "Son remakes SoftBank in his own image",
    summary: "The veteran investor has put himself at the centre of the global AI boom. Some think he now has too much control",
    body: "The veteran investor has put himself at the centre of the global AI boom. Some think he now has too much control",
    source: "Financial Times",
    url: "https://www.ft.com/content/a29a698c-3fb6-4e6f-ab02-1b7843786066",
    time: "10 min fa",
    pub_ts: 1783310413,
    tags: [],
  },
  {
    id: 60,
    cat: "economia-tech",
    title: "Rakuten Travel Xchange CEO on Japan's Tourism",
    summary: "James Park, CEO at Rakuten Travel Xchange, discusses the trends shaping Japan’s tourism market as inbound arrivals extended its decline in May, weighed down by reduced flights across routes and a prolonged slump in Chinese visitors. He speaks with Shery Ahn on \"Bloomberg: The Asia Trade.\" (Source: Bloomberg)",
    body: "James Park, CEO at Rakuten Travel Xchange, discusses the trends shaping Japan’s tourism market as inbound arrivals extended its decline in May, weighed down by reduced flights across routes and a prolonged slump in Chinese visitors. He speaks with Shery Ahn on \"Bloomberg: The Asia Trade.\" (Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-06/rakuten-travel-xchange-ceo-on-japan-s-tourism-video",
    time: "41 min fa",
    pub_ts: 1783308551,
    tags: [],
  },
  {
    id: 61,
    cat: "economia-tech",
    title: "ByteDance, Alibaba Pull AI Companions as Beijing Tightens Rules",
    summary: "ByteDance Ltd. and Alibaba Group Holding Ltd. are pulling the plug on features that let users build and chat with AI companions, preparing for new Chinese regulations governing human interactions with artificial intelligence.",
    body: "ByteDance Ltd. and Alibaba Group Holding Ltd. are pulling the plug on features that let users build and chat with AI companions, preparing for new Chinese regulations governing human interactions with artificial intelligence.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-06/bytedance-alibaba-pull-ai-companions-as-beijing-tightens-rules",
    time: "1 ora fa",
    pub_ts: 1783307031,
    tags: [],
  },
  {
    id: 62,
    cat: "economia-tech",
    title: "Converting car plants to make military drones will fail, warns Japan defence titan",
    summary: "Mitsubishi Heavy Industries chief says tactic risks being ‘enormous waste’ of taxpayers’ money",
    body: "Mitsubishi Heavy Industries chief says tactic risks being ‘enormous waste’ of taxpayers’ money",
    source: "Financial Times",
    url: "https://www.ft.com/content/31de8d91-4dd4-4dc0-a802-80dabd6ef9a2",
    time: "1 ora fa",
    pub_ts: 1783305227,
    tags: [],
  },
  {
    id: 63,
    cat: "economia-tech",
    title: "Self-Driving Startup Turing Gets AMD Backing, Adopts AMD GPUs",
    summary: "Self-driving tech developer Turing Inc. has added AMD Ventures to its list of backers and begun adopting Advanced Micro Devices Inc.’s AI accelerators in its systems.",
    body: "Self-driving tech developer Turing Inc. has added AMD Ventures to its list of backers and begun adopting Advanced Micro Devices Inc.’s AI accelerators in its systems.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-06/self-driving-startup-turing-gets-amd-backing-adopts-amd-gpus",
    time: "3 ore fa",
    pub_ts: 1783299635,
    tags: [],
  },
  {
    id: 64,
    cat: "economia-tech",
    title: "Samsung Union Leader’s $26 Billion Bonus Victory Turns to Bitterness",
    summary: "Avoiding old-school labor ideology, a new generation of tech workers finds itself divided by the AI boom.",
    body: "Choi Seung-ho, union leader at Samsung Electronics Co. in Pyeongtaek, South Korea, in June. Choi secured a staggering windfall for semiconductor workers who were promised bonuses of roughly $400,000 this year.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/features/2026-07-05/samsung-s-ai-bonus-deal-a-short-lived-victory-for-millennial-union-leader",
    time: "6 ore fa",
    pub_ts: 1783288820,
    tags: [],
  },
  {
    id: 65,
    cat: "economia-tech",
    title: "Netflix Viewers Are Abandoning Shows After One Season",
    summary: "Netflix’s biggest hits are losing more than half of their audience after one season",
    body: "Ted Sarandos, chief executive officer of Netflix Inc., during a Senate Judiciary Subcommittee on Antitrust, Competition Policy, and Consumer Rights hearing in Washington, DC, US, on Tuesday, Feb. 3, 2026. Netflix Inc. and Warner Bros. Discovery Inc. will face a skeptical Senate panel Tuesday to defend their $82.7 billion media merger against allegations it will hurt competition in the streaming market.\n\nPhotographer: Graeme Sloan/Bloomberg",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-05/netflix-viewers-are-abandoning-shows-after-one-season",
    time: "6 ore fa",
    pub_ts: 1783288801,
    tags: [],
  },
  {
    id: 66,
    cat: "economia-tech",
    title: "Fifa reverses suspension of star US striker after call from Trump",
    summary: "Belgium cries foul after governing body clears Folarin Balogun to play World Cup match",
    body: "Belgium cries foul after governing body clears Folarin Balogun to play World Cup match",
    source: "Financial Times",
    url: "https://www.ft.com/content/a858d225-59b8-4a85-866d-77055e7bfd58",
    time: "6 ore fa",
    pub_ts: 1783288022,
    tags: [],
  },
  {
    id: 67,
    cat: "economia-tech",
    title: "Hyundai Motor Showcases Humanoid at World Cup in Robotics Push",
    summary: "Hyundai Motor Co. showcased its Atlas humanoid robot at the 2026 FIFA World Cup, highlighting its technical progress on football’s biggest stage as the South Korean automaker gears up for mass production and factory deployment.",
    body: "Hyundai Motor Co. showcased its Atlas humanoid robot at the 2026 FIFA World Cup, highlighting its technical progress on football’s biggest stage as the South Korean automaker gears up for mass production and factory deployment.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-05/hyundai-motor-showcases-humanoid-at-world-cup-in-robotics-push",
    time: "6 ore fa",
    pub_ts: 1783287649,
    tags: [],
  },
  {
    id: 68,
    cat: "economia-tech",
    title: "AI Poses Biggest Security Challenge of Decade, UK’s Cooper Warns",
    summary: "The world must urgently develop guardrails to contain the threat posed by artificial intelligence, Britain’s foreign secretary is set to warn.",
    body: "The world must urgently develop guardrails to contain the threat posed by artificial intelligence, Britain’s foreign secretary is set to warn.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-05/ai-poses-biggest-security-challenge-of-decade-uk-s-cooper-warns",
    time: "6 ore fa",
    pub_ts: 1783287000,
    tags: [],
  },
  {
    id: 69,
    cat: "economia-tech",
    title: "Alibaba Gets Reprieve on Lobbying Ban Tied to DoD Blacklist",
    summary: "A federal judge ordered the Pentagon to give Alibaba Group Holding Ltd. a reprieve from a law that caused all of its lobbyists to drop it as a client while she considers the constitutionality of the measure, in a case set to test the US’s ability to curtail Chinese companies’ activities.",
    body: "A federal judge ordered the Pentagon to give Alibaba Group Holding Ltd. a reprieve from a law that caused all of its lobbyists to drop it as a client while she considers the constitutionality of the measure, in a case set to test the US’s ability to curtail Chinese companies’ activities.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-05/alibaba-gets-reprieve-from-lobbying-ban-tied-to-pentagon-s-curbs",
    time: "9 ore fa",
    pub_ts: 1783275617,
    tags: [],
  },
  {
    id: 70,
    cat: "economia-tech",
    title: "Universal’s Latest ‘Minions’ Delivers $61 Million in Debut",
    summary: "Minions &amp; Monsters, the seventh film in the animated franchise depicting the yellow, mischievous creatures who speak in expressive gibberish, was the highest-grossing movie over the July 4 holiday weekend, with $61.4 million in US and Canadian box office sales.",
    body: "Minions &amp; Monsters, the seventh film in the animated franchise depicting the yellow, mischievous creatures who speak in expressive gibberish, was the highest-grossing movie over the July 4 holiday weekend, with $61.4 million in US and Canadian box office sales.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-05/universal-s-latest-minions-delivers-64-million-in-film-debut",
    time: "12 ore fa",
    pub_ts: 1783266025,
    tags: [],
  },
  {
    id: 71,
    cat: "economia-tech",
    title: "Semiconductor Stocks Slide Amid AI Spending Concerns",
    summary: "Bloomberg Technology & Strategic Industries Senior Editor Mike Shepard says semiconductor stocks have come under pressure as investors question whether the rapid pace of AI infrastructure spending can be sustained beyond 2026, despite continued commitments from major technology companies. Shepard also explains to hosts of Bloomberg This Weekend David Gura and Christina Ruffini SK Hynix's planned…",
    body: "Bloomberg Technology & Strategic Industries Senior Editor Mike Shepard says semiconductor stocks have come under pressure as investors question whether the rapid pace of AI infrastructure spending can be sustained beyond 2026, despite continued commitments from major technology companies. Shepard also explains to hosts of Bloomberg This Weekend David Gura and Christina Ruffini SK Hynix's planned US ADR debut will give American investors easier access to one of the world's leading AI memory-chip suppliers while helping fund the company's continued expansion.\n\n(Source: Bloomberg)",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/videos/2026-07-05/semiconductor-stocks-slide-amid-ai-spending-concerns-video",
    time: "15 ore fa",
    pub_ts: 1783254313,
    tags: [],
  },
  {
    id: 72,
    cat: "economia-tech",
    title: "US voters say Trump’s Iran war not worth the cost — FT poll",
    summary: "Survey shows conflict is dragging down president’s approval ratings ahead of November midterms",
    body: "Survey shows conflict is dragging down president’s approval ratings ahead of November midterms",
    source: "Financial Times",
    url: "https://www.ft.com/content/f1fe0dae-d22b-4284-b0f9-fa10f717af1c",
    time: "16 ore fa",
    pub_ts: 1783252803,
    tags: [],
  },
  {
    id: 73,
    cat: "economia-tech",
    title: "Korea Considers New Investment Fund Using Tax Windfall From AI",
    summary: "South Korea is looking at creating an investment fund using excess tax revenue from its burgeoning semiconductor industry to finance long-term economic growth, a senior government official said.",
    body: "Th SK Hynix Inc. semiconductor plant under construction in Yongin, South Korea, on Tuesday, June 30, 2026. South Korean firms including Samsung and SK Hynix will spend at least 1,350 trillion won ($880 billion) on chips and data centers as the country seeks to maintain its edge in the AI era.",
    source: "Bloomberg Tech",
    url: "https://www.bloomberg.com/news/articles/2026-07-05/south-korea-eyes-growth-fund-from-chip-tax-windfall-yonhap-says",
    time: "16 ore fa",
    pub_ts: 1783252267,
    tags: [],
  },
];
